### ISSUE TITLE
Turkish Characters

### ISSUE THREAD

**Issue by itopal1** [moses-palmer/pynput#236] opened 2020-03-28 20:33 UTC
Could you please add Turkis characters also. (ıİğĞüÜşŞöÖçÇ)

**Comment by moses-palmer** [comment] 2020-03-28 20:51
If your current keyboard layout supports Turkish characters, this should be supported already. If it does not, *pynput* attempts to work around it on many platforms.

On what platform do you run *pynput*?

**Comment by itopal1** [comment] 2020-03-29 11:25
i tried win7 and win10 both 64bit and it gives for turkish characters the following error.

No handlers could be found for logger "pynput.keyboard.Listener"

Traceback (most recent call last):
  File "C:\Users\itopa\Desktop\test.py", line 23, in <module>
    listener.join()
  File "C:\Python27\lib\site-packages\pynput\_util\__init__.py", line 210, in join
    six.reraise(exc_type, exc_value, exc_traceback)
  File "C:\Python27\lib\site-packages\pynput\_util\__init__.py", line 162, in inner
    return f(self, *args, **kwargs)
  File "C:\Python27\lib\site-packages\pynput\keyboard\_win32.py", line 280, in _process
    self.on_press(key)
  File "C:\Python27\lib\site-packages\pynput\_util\__init__.py", line 78, in inner
    if f(*args) is False:
  File "C:\Users\itopa\Desktop\test.py", line 7, in on_press
    key.char))
UnicodeEncodeError: 'ascii' codec can't encode character u'\u011f' in position 0: ordinal not in range(128)

**Comment by itopal1** [comment] 2020-03-29 11:29
i am using the test code at https://pynput.readthedocs.io/en/latest/keyboard.html#monitoring-the-keyboard

**Comment by moses-palmer** [comment] 2020-03-29 18:41
Ah, that explains it!

The terminal in Windows does not handle Unicode very well; the error is actually caused by the Python runtime attempting to convert the Turkish character to ASCII.

To work around this, you may replace `key.char` with `repr(key.char)`.

I'm closing this issue, as it is unrelated to this library.

**Closed by moses-palmer** 2020-03-29 18:41 UTC
