### ISSUE TITLE
KeyError: undefined character name 'COMBINING DEGREE SIGN'

### ISSUE THREAD

**Issue by SpecialCharacter** [moses-palmer/pynput#41] opened 2017-08-18 08:41 UTC
Pynput gives me an error when I try to convert L° into L̥:
KeyError: "undefined character name 'COMBINING DEGREE SIGN'"

I think it is somwhere in __init__.py, six.py, _win32.py, or _base.py.

The line in question seems to be:
'COMBINING ' + unicodedata.name(self.char))

It should be COMBINING RING, not COMBINING DEGREE SIGN.

**Comment by moses-palmer** [comment] 2017-08-23 18:52
A degree sign is not a combining character.

When creating dead keys using [`pynput.keyboard.KeyCode`](https://github.com/moses-palmer/pynput/blob/master/lib/pynput/keyboard/_base.py#L134), *pynput* assumes that you pass the *non-combining* character for a dead key, such as `'~'` for *COMBINING TILDE U+0303*. To work around this, do the following:

    from pynput.keyboard import KeyCode

    dead = KeyCode(char='°')
    dead.is_dead = True
    dead.combining = u'\u0325'

    print(dead.join(KeyCode.from_char('L')))

**Comment by SpecialCharacter** [comment] 2017-08-24 07:41
Yes, this is exactly the problem.
I want to turn r° (degree sign) into r̥ (combining ring below), but the 
moment I type °, pynput stops working and throws an error.
It works fine with " and   ̋, so I think this is a bug.

**Comment by SpecialCharacter** [comment] 2017-08-24 07:49
key 'r' released
  r

Traceback (most recent call last):
   File 
"C:/Users/Bernd/AppData/Local/Programs/Python/Python36-32/string.latin_1.2-pynput38.py", 
line 1955, in <module>
     listener.join()
   File 
"C:\Users\Bernd\AppData\Local\Programs\Python\Python36-32\lib\site-packages\pynput\_util\__init__.py", 
line 185, in join
     six.reraise(exc_type, exc_value, exc_traceback)
   File 
"C:\Users\Bernd\AppData\Local\Programs\Python\Python36-32\lib\site-packages\six.py", 
line 685, in reraise
     raise value.with_traceback(tb)
   File 
"C:\Users\Bernd\AppData\Local\Programs\Python\Python36-32\lib\site-packages\pynput\_util\__init__.py", 
line 140, in inner
     return f(self, *args, **kwargs)
   File 
"C:\Users\Bernd\AppData\Local\Programs\Python\Python36-32\lib\site-packages\pynput\keyboard\_win32.py", 
line 232, in _process
     key = self._event_to_key(msg, vk)
   File 
"C:\Users\Bernd\AppData\Local\Programs\Python\Python36-32\lib\site-packages\pynput\keyboard\_win32.py", 
line 265, in _event_to_key
     msg in self._PRESS_MESSAGES))
   File 
"C:\Users\Bernd\AppData\Local\Programs\Python\Python36-32\lib\site-packages\pynput\keyboard\_base.py", 
line 49, in __init__
     'COMBINING ' + unicodedata.name(self.char))
KeyError: "undefined character name 'COMBINING DEGREE SIGN'"

vs

key 'r' released
r
key Key.shift_r released
key '*' released
r*
key Key.shift_r released
key '#' released
r*#
key Key.backspace released

key Key.backspace released

key Key.backspace released

key 'r' released
r
key '̥' released
r̥

**Comment by moses-palmer** [comment] 2017-08-24 11:07
So the crash happens in *pynput* without the callback ever reaching you code?

Does the following snippet cause the crash?

    from pynput import keyboard
    with keyboard.Listener() as listener:
        listener.join()

I don't have a degree sign on my keyboard, so I cannot test.

**Comment by SpecialCharacter** [comment] 2017-08-25 07:30
Exactly. It crashes in the moment I type ° (degree), i.e. BEFORE I have 
the chance to type #.
(I tried it out with R°= instead of R°#; it crashes too.)

Then I replaced

     with Listener(on_release=on_release) as listener:
         listener.join()

with your snippet.
It says:

Traceback (most recent call last):[st?rt]
   File 
"C:/Users/Bernd/AppData/Local/Programs/Python/Python36-32/snippet39.py", 
line 208, in <module>
     with keyboard.Listener() as listener:
AttributeError: 'Controller' object has no attribute 'Listener'

**Comment by SpecialCharacter** [comment] 2017-08-25 17:27
Actually, it crashes every time I type ° (degree), even if it is the first thing I do. 

Does your degree key work?

**Comment by moses-palmer** [comment] 2017-08-27 21:03
Unfortunately my keyboard does not have a degree sign, so I cannot really test it.

But if the crash happens inside *pynput* without even reaching your code, it is definitely a bug in the library.

It happens because *Windows*, when calling [MapVirtualKeyEx](https://msdn.microsoft.com/en-us/library/windows/desktop/ms646307(v=vs.85).aspx), sets the most significant bit, indicating that the character is a diacritic, or a dead character.

*pynput* works under the assumption that `MapVirtualKeyEx(MAPVK_VK_TO_CHAR, ...)` will return a pre-composed combining character in these cases, so that pressing for example the dead key marked _~_ will return _TILDE_. This does not appear to be the case. Is the degree sign an actual dead key on your keyboard? It seems reasonable to assume that it would then return [RING ABOVE](https://unicode-table.com/en/02DA/) instead of [DEGREE SIGN](https://unicode-table.com/en/00B0/).

**Comment by SpecialCharacter** [comment] 2017-08-28 08:20
Yes, it is Unicode Character 'DEGREE SIGN' (U+00B0).
But it doesn't matter, because as soon as I type °, /pynput/ crashes. No 
matter what character I typed before, even if it is the first character 
I type.

It is NOT a dead key! But I tried it with *# --> ˚  instead of °# --> ˚  
and it works just fine.
Can you somehow change your keyboard temporarily, maybe to US-international?
Because so far, it gives me 'combining degree sign' (instead of ring 
above/below) and crashes.

So I think something with |MapVirtualKeyEx(MAPVK_VK_TO_CHAR, ...) is not 
right.|

**Comment by moses-palmer** [comment] 2019-12-04 07:22
@SpecialCharacter, does this still happen with the _master_ branch with a corrected keyboard listener?

**Comment by moses-palmer** [comment] 2020-01-08 14:24
This is a duplicate of #199, which has more recent activity, so I will close this issue.

**Closed by moses-palmer** 2020-01-08 14:24 UTC
