### ISSUE TITLE
Using event suppression to create a remapper

### ISSUE THREAD

**Issue by TheoRet** [moses-palmer/pynput#105] opened 2018-08-11 20:14 UTC
Hello moses-palmer, thanks for the latest release 1.4!

I am using Linux Mint MATE 18.3 and python 3.5.2.

Now that there is a suppress option for the listener, I am trying to build a key remapper based on pynput. For this, I want to use suppress = True and then Controller.press() / Controller.release() to resend the  (potentially) modified keys.  The following example is based on the keyboard.Listener documentation and simply tries to forward all key events without modification:

```
from pynput import keyboard
c = keyboard.Controller()
import time

ignore_p = False
ignore_r = False

def on_press(key):
    global ignore_p
    if ignore_p:
        ignore_p = False
        print(key, "press ignored")
        return
    ignore_p = True
    try:
        print('alphanumeric key {0} pressed'.format(key.char))
        c.press(key.char)
    except AttributeError:
        print('special key {0} pressed'.format(key))
        c.press(key)
    

def on_release(key):
    global ignore_r
    if ignore_r:
        ignore_r = False
        print(key, "release ignored")
        return
    ignore_r = True
    try:
        print('alphanumeric key {0} released'.format(key.char))
        c.release(key.char)
    except AttributeError:
        print('special key {0} released'.format(key))
        c.release(key)
    

# Collect events until released
with keyboard.Listener(
        on_press=on_press,
        on_release=on_release, suppress=True) as listener:
    time.sleep(30)
```

- Problem 1:  How to make pynput ignore the events injected by itself?  My workaround in the example above is actually performing well so far. but it seems quite ugly and might be problematic if there are other events being received simultaneously. Do you see any better option?
EDIT:  I have seen in #69 that you are already working on detecting injected events in a separate fork. That sounds promising! :-)

- Problem 2: calling c.press/c.release for alphanumeric keys while suppress = True worked nicely.  However, special keys  (like tab, space, backspace,..) injected by c.press / c.release were ignored on my machine -- except for modifiers/ dead keys which still worked with suppress active.

**Comment by TheoRet** [comment] 2018-08-11 21:44
Ok, I tested the injected branch with the standard usage examples for keyboard / mouse listeners and sending a fake event using Controller.press.  As expected, fake detection worked properly for the keyboard, but not for the mouse.

The simplified version of my example:
```
from pynput import keyboard
c = keyboard.Controller()
import time

def on_press(key, inject):
    if inject: return
    try:
        print('alphanumeric key {0} pressed'.format(key.char))
        c.press(key.char)
    except AttributeError:
        print('special key {0} pressed'.format(key))
        c.press(key)


def on_release(key, inject):
    if inject: return
    try:
        print('alphanumeric key {0} released'.format(key.char))
        c.release(key.char)
    except AttributeError:
        print('special key {0} released'.format(key))
        c.release(key)


# Collect events until released
with keyboard.Listener(on_press=on_press, on_release=on_release,
        suppress=True) as listener:
    time.sleep(30)
```

So problem 1 is solved for the keyboard case.

Will pynput only recognize events injected by itself or also by other programs?
And there is absolutely no way to implement the inject feature for mouse buttons on Xorg? Because I would also like to remap them.

Comment on the API: Introducing the inject argument to callback functions will break backward compatibility, won't it? However, leaving away the inject argument does not create an error, as it should, but it rather creates confusing key events.

**Comment by moses-palmer** [comment] 2018-08-13 07:48
That's a lot of questions :-)

Regarding *problem 1*: I have not yet merged [`feature-injected`](https://github.com/moses-palmer/pynput/tree/feature-injected), because detection of injected events is not reliable on all supported platforms. As you can see in commit [`c05c3a1`](https://github.com/moses-palmer/pynput/commit/c05c3a1e9d2a735a9c2d43757fed871c8d687685), it works on *Xorg* only because injected events are forwarded manually. I have not yet found a way to distinguish injected events from authentic input events on *Linux*.

Until this is resolved, this limitation is noted in commit [`7a14064`](https://github.com/moses-palmer/pynput/commit/7a140645fbe526e968ccf8080292997f33448199).

I introduced an extra argument specifically to not break the API---I did not want to modify the event objects. If the callback does not accept the `injected` argument, it is not passed. Since the branch is not yet merged, this may change if found to be too confusing.

Regarding *problem 2*: Since handling of fake events in *pynput* does not differ between alphanumeric keys and control keys, I assume this is caused by something inside the X server.

**Comment by moses-palmer** [comment] 2018-09-07 19:09
On a side note, I was wondering why you used `c.press(key.char)` instead of `c.press(key)`, and noticed that doing so would cause *pynput* to crash since the virtual key code stored in the event was a key code and not a keysym. This has been corrected in *master*.

**Comment by TheoRet** [comment] 2018-09-09 21:42
Thanks for improving this! It confused me too at first.

To understand what the commit c05c3a1 is doing:
Xorg does not provide you with an option to distinguish injected events, so you implemented a workaround purely inside pynput?  This would be all we need to solve problem 1 on any platform! 
In this workaround, how do you manage to not detect the c.press(key) event 2 times?  (First when forwarding it and second when actually sending it to the system?)

**Comment by 256shadesofgrey** [comment] 2020-02-28 14:13
@TheoRet Have you been able to resolve the 2nd issue? I'm trying to do something similar now (only intercept certain keybinds and "pass through" the rest), but keys like backspace or arrow keys do not work.

**Comment by TheoRet** [comment] 2020-03-03 23:58
no I have not further investigated into this. Instead I use a solution based on evdev, which seems the best option for remapping in case you are using Linux.

**Comment by moses-palmer** [comment] 2020-03-04 06:12
With progress on an *uinput* based backend ongoing in #184, I will close this issue.

**Closed by moses-palmer** 2020-03-04 06:12 UTC
