### ISSUE TITLE
Remembers ctrl and shift after release

### ISSUE THREAD

**Issue by arcane99** [moses-palmer/pynput#2] opened 2016-09-21 20:17 UTC
Good day, thanks for creating this great library.

Python 2.7, release 1.1 of pynput, Windows 10

I am experiencing an odd issue with the keyboard monitor and control/shift keys.

On release of the control or shift key, the application remembers the key and the next input logged is then a special character. 
For example 
- if I press 'a' and release, keyboard monitor logs a u'a'
- if I press 'left control' and release, keyboard monitor logs a 'Key.ctrl_l'
- if I then press 'a' and release, keyboard monitor logs a u'\x01'
- if I then press 'a' and release again, keyboard monitor logs a u'a'

A similar thing is observed with the shift key. A capital 'A' is recognized on press of 'a' (without the shift). This means that the key press logged after a control or shift press and release is incorrect.

Not sure if this is in fact a pynput issue. 

Regards

**Comment by moses-palmer** [comment] 2016-09-21 20:23
Thank you for the report. I will look into it in the coming days, as I
think it definitely is a pynput issue; control keys on Windows are among
the more challenging parts of the library.

Could you tell me what keyboard layout you use?

**Comment by arcane99** [comment] 2016-09-21 20:55
Hi.  It's a standard US keyboard layout, no custom keys. I can test with a
different layout tomorrow. I'll also see if I can replicate on a Linux
machine.

Just so you are aware there is a typo in mouse monitor on_scroll example in
documentation,  the function is missing the x and y parameters.

def on_scroll(dx, dy): should be

def on_scroll(x,y,dx, dy):

Regards

**Comment by moses-palmer** [comment] 2016-09-22 11:35
After further investigation, I have located the error to [ToUnicodeEx](https://msdn.microsoft.com/en-us/library/windows/desktop/ms646322(v=vs.85).aspx).

The issue is not limited to *ctrl*; pressing *shift* also keeps the state until the next key press. I will look into the keyboard state buffer returned by [GetKeyboardState](https://msdn.microsoft.com/en-us/library/windows/desktop/ms646299%28v=vs.85%29.aspx?f=255&MSPPError=-2147217396).

**Comment by moses-palmer** [comment] 2016-09-25 22:18
I have an attempt at a solution ready [here](https://github.com/moses-palmer/pynput/tree/fixup-listeners).

It fixes the issue by postponing handling and sending the keyboard event until all system hooks have executed by posting a message to the listener main loop. According to the documentation of [LowLevelKeyboardProc](https://msdn.microsoft.com/en-us/library/windows/desktop/ms644985(v=vs.85).aspx), the keyboard state is not updated during the system hook callback, and thus `GetKeyboardState` will return an incorrect shift state.

Please note that this bug fix required a rather large rewrite of the *Windows* backend. I have not yet merged the fixup branch into master as I will need to add some tests, and figure out a way to actually have the tests pass on Windows.

I would appreciate your feedback on the bugfix, especially if actually resolves the issues of your use case, and whether you notice any regressions.

**Comment by arcane99** [comment] 2016-09-26 05:58
Okay,  will do.  Give me a day or two.

What other changes should I expect as a result of the fix? Is it working as
expected in your testing now?

On 26 Sep 2016 12:18 AM, "moses-palmer" <notifications@github.com> wrote:

I have an attempt at a solution ready here
<https://github.com/moses-palmer/pynput/tree/fixup-listeners>.

It fixes the issue by postponing handling and sending the keyboard event
until all system hooks have executed by posting a message to the listener
main loop. According to the documentation of LowLevelKeyboardProc
<https://msdn.microsoft.com/en-us/library/windows/desktop/ms644985(v=vs.85).aspx>,
the keyboard state is not updated during the system hook callback, and thus
GetKeyboardState will return an incorrect shift state.

Please note that this bug fix required a rather large rewrite of the
*Windows* backend. I have not yet merged the fixup branch into master as I
will need to add some tests, and figure out a way to actually have the
tests pass on Windows.

I would appreciate your feedback on the bugfix, especially if actually
resolves the issues of your use case, and whether you notice any
regressions.

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/moses-palmer/pynput/issues/2#issuecomment-249450297>,
or mute the thread

**Comment by moses-palmer** [comment] 2016-09-26 06:07
The fix changes the code only for the keyboard listener, so no other parts
of the library should be affected.

All simple keyboard listener tests pass, as does a sample app to mimic the
behaviour you described in this but report. Unfortunately, because of the
terrible terminal support on Windows, many of the keyboard tests do not,
and never have.

Before merging this branch, I will add a test for modifier keys, and I will
look into finding a way to make the tests pass on Windows as well.

**Comment by moses-palmer** [comment] 2016-09-26 13:22
I did discover another bug in the _Windows_ backend, and after resolving it all tests except the one depending on the terminal encoding (faking typing a non-ASCII string and reading it from _stdin_) pass, so I have merged the fixup branch and made a release.

Thank you again for your report. I will now close this issue.

**Closed by moses-palmer** 2016-09-26 13:22 UTC

**Comment by arcane99** [comment] 2016-09-26 18:13
Hi. Performing a pip install --upgrade; gives the following error now
Traceback (most recent call last):
  File " automateitcapture.py", line 4, in <module>
    from pynput import mouse,keyboard
  File " lib\site-packages\pynput\__init__.py", line 18, in <module>
    from . import keyboard
  File " lib\site-packages\pynput\keyboard\__init__.py", line 36, in <module>
    from ._win32 import KeyCode, Key, Controller, Listener
  File " lib\site-packages\pynput\keyboard\_win32.py", line 21, in <module>
    from pynput._util.win32 import *
  File " lib\site-packages\pynput\_util\win32.py", line 374, in <module>
    class KeyTranslator(object):
  File " lib\site-packages\pynput\_util\win32.py", line 392, in KeyTranslator
    wintypes.LPDWORD)
AttributeError: 'module' object has no attribute 'LPDWORD'

**Comment by moses-palmer** [comment] 2016-09-26 18:31
Sorry about that---it appears that `LPDWORD` was introduced in *Python 3.2*.

I have uploaded a new release with a fix.

**Comment by arcane99** [comment] 2016-09-26 18:54
Thanks for the extremely quick responses. Working great now.

Ps: Do you sleep? ;)

**Comment by moses-palmer** [comment] 2016-09-26 19:17
Great to hear!

Yes, I do sleep; it's the magic of time zones at work ;-)
