### ISSUE TITLE
Global hotkeys with F1 and F12 don't work on MacOS

### ISSUE THREAD

**Issue by jiayouzl** [moses-palmer/pynput#503] opened 2022-10-05 06:40 UTC
```
keyboard.HotKey.parse('<ctrl>+<alt>'),#yes
keyboard.HotKey.parse('<ctrl>+c'),#yes
```
macos The above 2 lines of code are normal
```
keyboard.HotKey.parse('<ctrl>+<f1>'),#no
keyboard.HotKey.parse('<f2>'),#no
keyboard.HotKey.parse('<f3>'),#no
keyboard.HotKey.parse('<f4>'),#no
keyboard.HotKey.parse('<f11>'),#no
```
macos The above 5 lines of code cannot be used normally.

```
# -*- coding: UTF-8 -*-

from pynput import keyboard

def on_activate():
    print('Global hotkey activated!')

def for_canonical(f):
    return lambda k: f(l.canonical(k))

hotkey = keyboard.HotKey(
    # keyboard.HotKey.parse('<ctrl>+<alt>'),#Normal
    # keyboard.HotKey.parse('<ctrl>+c'),#Normal
    keyboard.HotKey.parse('<ctrl>+<f1>'),#Invalid, abnormal
    # keyboard.HotKey.parse('<f2>'),#Invalid, abnormal
    # keyboard.HotKey.parse('<f3>'),#Invalid, abnormal
    # keyboard.HotKey.parse('<f4>'),#Invalid, abnormal
    # keyboard.HotKey.parse('<f11>'),#Invalid, abnormal
    on_activate)
with keyboard.Listener(
        on_press=for_canonical(hotkey.press),
        on_release=for_canonical(hotkey.release)) as l:
    l.join()
```

<img width="432" alt="image" src="https://user-images.githubusercontent.com/7685337/193997105-50efa728-fa1c-48e1-9385-d2c425b3bd5b.png">

**Comment by jiayouzl** [comment] 2022-10-05 14:09
```
from pynput import keyboard

def on_activate_f1():
    print('<f1> pressed')

with keyboard.GlobalHotKeys({
        '<f1>': on_activate_f1
}) as h:
    h.join()
```

This writing is also invalid.

**Comment by jiayouzl** [comment] 2022-10-05 14:16
2022-10-05
> I just found the above code invalid in Windows10 21H2. Can't operate normally.

> Everything is normal except the f1-f12 key.

**Comment by moses-palmer** [comment] 2022-10-13 16:55
Thank you for your report.

There has been a regression in the parsing and handling of hotkeys, a fix for which I just pushed. Do you have the possibility to test *pynput* from the *master* branch and see if any of your issues is resolved?

**Comment by jiayouzl** [comment] 2022-10-18 02:18
Use pip install git+https://github.com/moses-palmer/pynput.git
Problem solved

**Comment by moses-palmer** [comment] 2022-10-19 14:05
Thank you for your response. I will close this issue as soon as a new version is released.

**Comment by hiroi-sora** [comment] 2022-10-29 16:34
I had the same problem in Windows10. HotKey `<F1>` don't work.

Master branch updated on 2 Jan, is fix included?

**Comment by jiayouzl** [comment] 2022-11-13 14:38
> Thank you for your response. I will close this issue as soon as a new version is released.

When will the new version be released? Now it can only be installed through GitHub, and distribution is very inconvenient.

**Comment by jiayouzl** [comment] 2022-12-27 14:28
hello?

**Comment by jiayouzl** [comment] 2023-10-09 05:56
When will the new version be released? Now it can only be installed through GitHub, and distribution is very inconvenient.~

**Closed** 2024-07-07 07:26 UTC

**Comment by moses-palmer** [comment] 2024-07-09 18:53
@jiayouzl, thank you for closing the issue, and I apologise for not reaching out earlier; I do get quite a lot of email from *github*, so I missed your messages.

I assume that you closed it because the new released version fixed the issue?
