### ISSUE TITLE
Pynput "Return" key not sent when using Discord

### ISSUE THREAD

**Issue by Piero-Bird** [moses-palmer/pynput#34] opened 2017-06-23 21:43 UTC
Hello, I've recently run in to a strange problem when using pynput. When listening to the keyboard on my machine whenever I open Discord (https://discordapp.com/) desktop application (and some other apps) and type a message - then press "Enter" the key is never sent? I've actually just gotten the "enter" key to send closing out of some background applications, so my assumption is this is due to some kind of computer stress?

I noticed if I spam the key it'll go through as well, and pynput still captures it regardless. If this isn't a pynput issue or there's something I'm missing I apologize.

**Comment by moses-palmer** [comment] 2017-06-24 17:16
Did you find out what caused the issue?

**Comment by Piero-Bird** [comment] 2017-06-24 17:56
I thought I did, but it happened again today. I'm re-opening then.

**Comment by moses-palmer** [comment] 2017-09-17 13:51
I have created issue #49 as a container for all *win32 keyboard listener* related issues, as I suspect that the root cause is the same.

I will close this issue. If you think the problem is unrelated to #49, please reopen this issue.

**Closed by moses-palmer** 2017-09-17 13:51 UTC
