### ISSUE TITLE
Doesnt work when I try "from pynput.mouse import Button, Controller"

### ISSUE THREAD

**Issue by atesbey12** [moses-palmer/pynput#145] opened 2019-03-25 16:09 UTC
I am on Windows 10 and trying to start using pynput but when I enter the first line:
from pynput.mouse import Button, Controller

There is an issue as when I run it, it says:
ImportError: No module named pynput.mouse

Can someone please help

**Comment by moses-palmer** [comment] 2019-03-31 19:00
Thank you for your report.

Have you installed *pynput* using `pip install pynput` before running your code?

**Comment by CrisisLP** [comment] 2019-04-23 23:40
Can confirm using pip Version: 19.0.3|Python 3.7 . Only work if I use `Import pynput`. Also cant start with this.

**Comment by moses-palmer** [comment] 2019-11-29 07:29
I'm sorry, but I cannot reproduce this. I have tested with _pip 19.3.1_ and _Python 3.7_ running under _Windows 10_.

I will close this issue, as I think it is related to the environment and _pynput_. Please reopen if you think otherwise.

**Closed by moses-palmer** 2019-11-29 07:29 UTC

**Comment by dogman1223** [comment] 2025-01-23 19:14
python 3.13- using pynput 
pynput successfully installed and functioning as far as i can tell 
im trying to run a mouse controller .

from pynput.mouse import Button, Controller
def controller():
    mouse=Controller
    mouse,postion = (10,20)
controller()

this stack runs but does not move my mouse im going to slam my head into a wall. help plz

**Comment by glauciofonsecaa** [comment] 2025-01-23 19:31
> python 3.13- using pynput pynput successfully installed and functioning as far as i can tell im trying to run a mouse controller .
> 
> from pynput.mouse import Button, Controller def controller(): mouse=Controller mouse,postion = (10,20) controller()
> 
> this stack runs but does not move my mouse im going to slam my head into a wall. help plz

You made a mistake in mouse,position. You put a , instead of . The correct one would be mouse.position(10, 20)

**Comment by dogman1223** [comment] 2025-01-23 19:34
Okay I fized that but it still doesn't move my cursor it just runs the
program and does nothing

**Comment by glauciofonsecaa** [comment] 2025-01-23 19:38
> python 3.13- using pynput pynput successfully installed and functioning as far as i can tell im trying to run a mouse controller .
> 
> from pynput.mouse import Button, Controller def controller(): mouse=Controller mouse,postion = (10,20) controller()
> 
> this stack runs but does not move my mouse im going to slam my head into a wall. help plz

`from pynput.mouse import Button, Controller
def controller():
    mouse = Controller()
    mouse.position(10, 20)
controller()`

**Comment by glauciofonsecaa** [comment] 2025-01-23 19:47
![Image](https://github.com/user-attachments/assets/8fae262a-7b5f-4941-8e8e-6adbcd273db0)

**Comment by dogman1223** [comment] 2025-01-23 19:50
Haha, thanks! You guys were all a big help

**Comment by dogman1223** [comment] 2025-01-24 13:56
from pynput.keyboard import Key, Listener
def writetofile(Key):
    keydata=str(Key)
    with open("dickhead.txt", 'a') as f:
        f.write(keydata)
with Listener(on_press = writetofile) as l:
    l.join() 
okay in theory this sapost to open a file and save my keystokes to it but the file "dickhead.txt" isnt opening

**Comment by dogman1223** [comment] 2025-01-24 14:35
i thinks its something to so with the def comand in line 2 without it the file opens but then the rest of code breaks down so im at a loss

**Comment by glauciofonsecaa** [comment] 2025-01-24 15:24
> from pynput.keyboard import Key, Listener def writetofile(Key): keydata=str(Key) with open("dickhead.txt", 'a') as f: f.write(keydata) with Listener(on_press = writetofile) as l: l.join() okay in theory this sapost to open a file and save my keystokes to it but the file "dickhead.txt" isnt opening

![Image](https://github.com/user-attachments/assets/cbca4738-0cc8-43e4-bb65-3e5da7937b4f)

**Comment by dogman1223** [comment] 2025-01-24 15:43
okay that kind of fixed it but its only tracking the the backspace and enter keys also why does that work? i also found out it doesnt like when i add .txt to the file name for some reason

**Comment by dogman1223** [comment] 2025-01-27 14:56
from pynput.keyboard import Listener, Key
def on_press(Key):
    try:
        with open("famdogg",'a') as log_file:
            log_file.write("Alphanumeric key pressed", {Key.char})
    except:
        pass
        log_file.write("special key presse", {Key})
    def on_release (Key):
        if Key == Key.esc:
            return False 
        with keyboard.Listener(on_press=on_press, on_release=on_release) as Listener:
            Listener.join()
its not opening the file again. I'm very confused about why
