### ISSUE TITLE
can't listen mouse when mouse in windows Task Manager

### ISSUE THREAD

**Issue by dade68** [moses-palmer/pynput#489] opened 2022-07-21 11:34 UTC
**Description**
when move mouse in windos task mannger, listener can't capture mouse positon and movement

**Platform and pynput version**
Windows10

**To Reproduce**
from pynput import keyboard
from pynput import mouse
from datetime import datetime

def on_press(key):
    try:
        print(f'{key.char} down')
    except AttributeError:
        print(f'{key} down')

def on_release(key):
    print(f'{key} up')

def on_move(x, y):
    print('move to ', x, y)

def on_click(x, y, button, pressed):
    if pressed == False:
        print('click at ', x, y, button, pressed)
        print(datetime.now().isoformat(timespec='microseconds'))

def on_scroll(x, y, dx, dy):
    print('scroll at ', x, y, 'by', dx, dy)

def listen_mouse():
    listener = mouse.Listener(
        on_move=None,
        on_click=on_click,
        on_scroll=on_scroll
    )
    listener.start()

if __name__ == '__main__':
    listen_mouse()
    while True:
        pass

**Comment by dade68** [comment] 2022-07-21 11:36
i found that the listener function can't listen mouse when mouse move in some windows, such as task manager in windows system

**Comment by moses-palmer** [comment] 2022-07-21 20:02
Thank you for your report.

This is caused by the Windows access control and isa security feature of the operating system. The limitation cannot be worked around in this library, so I will close this issue as there is unfortunately nothing to do.

**Closed by moses-palmer** 2022-07-21 20:02 UTC
