### ISSUE TITLE
When Suppress=True, X crashes 

### ISSUE THREAD

**Issue by vipow** [moses-palmer/pynput#275] opened 2020-06-06 03:06 UTC
Environment: Ubuntu20.04 (running on Windows10 Pro with VMware Workstation Player 15)

sample.py
```python3
from pynput import mouse

def on_move(x, y):
    print('Pointer moved to {0}'.format(
        (x, y)))

def on_click(x, y, button, pressed):
    print('{0} at {1}'.format(
        'Pressed' if pressed else 'Released',
        (x, y)))
    if not pressed:
        # Stop listener
        return False
def on_scroll(x, y, dx, dy):
    print('Scrolled {0} at {1}'.format(
        'down' if dy < 0 else 'up',
        (x, y)))

# Collect events until released
with mouse.Listener(
        on_move=on_move,
        on_click=on_click,
        on_scroll=on_scroll,
        suppress=True
        ) as listener:
    listener.join()

```

```
$ python3 sample.py 
Pointer moved to (295, 945)
Pointer moved to (295, 947)
Pointer moved to (294, 951)
Pointer moved to (294, 953)
Pointer moved to (295, 956)
Pointer moved to (295, 957)
Pressed at (295, 957)
Released at (295, 957)
$
```

First start the sample program as above, then click to exit.
After that, when I do a few operations, such as starting firefox, it always logs out suddenly.

**Comment by moses-palmer** [comment] 2020-07-06 22:17
Thank you for your report, but this appears to be a duplicate of #269, so I'll close this issue to keep the number of open issues manageable.

**Closed by moses-palmer** 2020-07-06 22:17 UTC
