### ISSUE TITLE
Media keys recorded on pressing regular characters

### ISSUE THREAD

**Issue by pedrorrivero** [moses-palmer/pynput#201] opened 2019-12-16 01:03 UTC
In the new MacBook Pro with touchbar (european spanish keyboard) whenever letter `a` is pressed, the actual recorded key is Key.media_volume_up. This is not the only case:

- `a` : Key.media_volume_up
- `s` : Key.media_volume_down
- `t` : Key.media_next
- `y` : Key.media_play_pause
- `x` : Key.media_volume_mute
- `1` : Key.media_previous

**Comment by moses-palmer** [comment] 2019-12-18 18:27
Thank you for your report.

This was unfortunate. I no longer have access to a _macOS_ system, so it is very difficult to test new features. I have published an attempt at fixing this as the branch [fixup-osx-media-keys](https://github.com/moses-palmer/pynput/tree/fixup-osx-media-keys). Is it possible for you to test it?

If it does not work, could you add som logging to the keyboard events to [line 283 of `lib/pynput/keyboard/_darwin.py`](https://github.com/moses-palmer/pynput/blob/c78dca88d97c43d48abbd4a518ff5f89e2c3bc70/lib/pynput/keyboard/_darwin.py#L283)?

**Comment by pedrorrivero** [comment] 2019-12-19 08:23
For some reason I am getting some errors. This is what I am doing:
```
$ virtualenv pynput-venv
  ···
$ source pynput-venv/bin/activate
(pynput-venv) $ pip install git+https://github.com/moses-palmer/pynput.git@fixup-osx-media-keys
  ···
```
```
(pynput-venv) $ python3 run-keylogger.py

Unhandled exception in listener callback
Traceback (most recent call last):
  File "/Users/pedrorrivero/test-dir/pynput-venv/lib/python3.7/site-packages/pynput/_util/__init__.py", line 162, in inner
    return f(self, *args, **kwargs)
  File "/Users/pedrorrivero/test-dir/pynput-venv/lib/python3.7/site-packages/pynput/_util/darwin.py", line 261, in _handler
    self._handle(proxy, event_type, event, refcon)
  File "/Users/pedrorrivero/test-dir/pynput-venv/lib/python3.7/site-packages/pynput/keyboard/_darwin.py", line 237, in _handle
    key = self._event_to_key(event)
  File "/Users/pedrorrivero/test-dir/pynput-venv/lib/python3.7/site-packages/pynput/keyboard/_darwin.py", line 283, in _event_to_key
    is_media = event.type == NSSystemDefined
AttributeError: 'CGEventRef' object has no attribute 'type'
Traceback (most recent call last):
  File "run-keylogger.py", line 23, in <module>
    my_keylogger.start()
  File "/Users/pedrorrivero/test-dir/keylogger.py", line 86, in start
    listener.join()
  File "/Users/pedrorrivero/test-dir/pynput-venv/lib/python3.7/site-packages/pynput/_util/__init__.py", line 210, in join
    six.reraise(exc_type, exc_value, exc_traceback)
  File "/Users/pedrorrivero/test-dir/pynput-venv/lib/python3.7/site-packages/six.py", line 695, in reraise
    raise value.with_traceback(tb)
  File "/Users/pedrorrivero/test-dir/pynput-venv/lib/python3.7/site-packages/pynput/_util/__init__.py", line 162, in inner
    return f(self, *args, **kwargs)
  File "/Users/pedrorrivero/test-dir/pynput-venv/lib/python3.7/site-packages/pynput/_util/darwin.py", line 261, in _handler
    self._handle(proxy, event_type, event, refcon)
  File "/Users/pedrorrivero/test-dir/pynput-venv/lib/python3.7/site-packages/pynput/keyboard/_darwin.py", line 237, in _handle
    key = self._event_to_key(event)
  File "/Users/pedrorrivero/test-dir/pynput-venv/lib/python3.7/site-packages/pynput/keyboard/_darwin.py", line 283, in _event_to_key
    is_media = event.type == NSSystemDefined
AttributeError: 'CGEventRef' object has no attribute 'type'
```
These errors pop-up as soon as I hit any key, however, this does not occur on the master branch version of the code.

**Comment by moses-palmer** [comment] 2019-12-19 08:38
Thank you for testing!

The line causing the error is new. The reason letters are mixed up with media keys is that they share virtual key codes, so we need a way to determine whether events are caused by media keys, but the documentation is somewhat lacking.

Do you think you could attempt a debugging session? Install `pudb` and insert the line `import pudb; pudb.set_trace()` just before `pynput/keyboard/_darwin.py:238` and then inspect the event object.

**Comment by pedrorrivero** [comment] 2019-12-19 08:40
I am going to be traveling for the next couple of weeks but I'll give it a try if I find the time! I will make sure to keep you posted. Merry Christmas!

**Comment by moses-palmer** [comment] 2019-12-19 08:45
Thank you, and have a merry Christmas!

**Comment by jangid** [comment] 2019-12-24 11:25
I can do this debugging. But I don't know how to use pudb, as of now. Let me read some docs then respond. Although I have inserted the line `import pudb; pudb.set_trace()` exactly at the line no. that you have specified. But that is not giving any different output. Same stacktrace.

**Comment by moses-palmer** [comment] 2019-12-24 12:38
Thank you for your offer!

I actually specified the wrong line number; it's actually 284, just before `is_media = event.type == NSSystemDefined`.

**Comment by jangid** [comment] 2019-12-24 16:19
This is the output when I press 'a'.

```
pankaj@Pankajs-MacBook-Pro pynput % python t.py
Unhandled exception in listener callback
Traceback (most recent call last):
  File "lib/pynput/_util/__init__.py", line 162, in inner
    return f(self, *args, **kwargs)
  File "lib/pynput/_util/darwin.py", line 261, in _handler
    self._handle(proxy, event_type, event, refcon)
  File "lib/pynput/keyboard/_darwin.py", line 237, in _handle
    key = self._event_to_key(event)
  File "lib/pynput/keyboard/_darwin.py", line 283, in _event_to_key
    import pudb; pudb.set_trace()
  File "/Users/pankaj/work/code/github/pynput/.direnv/python-venv-3.7.3/lib/python3.7/site-packages/pudb/__init__.py", line 232, in set_trace
    dbg = _get_debugger()
  File "/Users/pankaj/work/code/github/pynput/.direnv/python-venv-3.7.3/lib/python3.7/site-packages/pudb/__init__.py", line 109, in _get_debugger
    from pudb.debugger import Debugger
  File "/Users/pankaj/work/code/github/pynput/.direnv/python-venv-3.7.3/lib/python3.7/site-packages/pudb/debugger.py", line 32, in <module>
    import urwid
  File "/Users/pankaj/work/code/github/pynput/.direnv/python-venv-3.7.3/lib/python3.7/site-packages/urwid/__init__.py", line 26, in <module>
    from urwid.widget import (FLOW, BOX, FIXED, LEFT, RIGHT, CENTER, TOP, MIDDLE,
  File "/Users/pankaj/work/code/github/pynput/.direnv/python-venv-3.7.3/lib/python3.7/site-packages/urwid/widget.py", line 27, in <module>
    from urwid.util import (MetaSuper, decompose_tagmarkup, calc_width,
  File "/Users/pankaj/work/code/github/pynput/.direnv/python-venv-3.7.3/lib/python3.7/site-packages/urwid/util.py", line 61, in <module>
    detected_encoding = detect_encoding()
  File "/Users/pankaj/work/code/github/pynput/.direnv/python-venv-3.7.3/lib/python3.7/site-packages/urwid/util.py", line 44, in detect_encoding
    initial = locale.getlocale()
  File "/Applications/Xcode.app/Contents/Developer/Library/Frameworks/Python3.framework/Versions/3.7/lib/python3.7/locale.py", line 587, in getlocale
    return _parse_localename(localename)
  File "/Applications/Xcode.app/Contents/Developer/Library/Frameworks/Python3.framework/Versions/3.7/lib/python3.7/locale.py", line 495, in _parse_localename
    raise ValueError('unknown locale: %s' % localename)
ValueError: unknown locale: UTF-8
Traceback (most recent call last):
  File "t.py", line 27, in <module>
    listener.join()
  File "lib/pynput/_util/__init__.py", line 210, in join
    six.reraise(exc_type, exc_value, exc_traceback)
  File "/Users/pankaj/work/code/github/pynput/.direnv/python-venv-3.7.3/lib/python3.7/site-packages/six.py", line 695, in reraise
    raise value.with_traceback(tb)
  File "lib/pynput/_util/__init__.py", line 162, in inner
    return f(self, *args, **kwargs)
  File "lib/pynput/_util/darwin.py", line 261, in _handler
    self._handle(proxy, event_type, event, refcon)
  File "lib/pynput/keyboard/_darwin.py", line 237, in _handle
    key = self._event_to_key(event)
  File "lib/pynput/keyboard/_darwin.py", line 283, in _event_to_key
    import pudb; pudb.set_trace()
  File "/Users/pankaj/work/code/github/pynput/.direnv/python-venv-3.7.3/lib/python3.7/site-packages/pudb/__init__.py", line 232, in set_trace
    dbg = _get_debugger()
  File "/Users/pankaj/work/code/github/pynput/.direnv/python-venv-3.7.3/lib/python3.7/site-packages/pudb/__init__.py", line 109, in _get_debugger
    from pudb.debugger import Debugger
  File "/Users/pankaj/work/code/github/pynput/.direnv/python-venv-3.7.3/lib/python3.7/site-packages/pudb/debugger.py", line 32, in <module>
    import urwid
  File "/Users/pankaj/work/code/github/pynput/.direnv/python-venv-3.7.3/lib/python3.7/site-packages/urwid/__init__.py", line 26, in <module>
    from urwid.widget import (FLOW, BOX, FIXED, LEFT, RIGHT, CENTER, TOP, MIDDLE,
  File "/Users/pankaj/work/code/github/pynput/.direnv/python-venv-3.7.3/lib/python3.7/site-packages/urwid/widget.py", line 27, in <module>
    from urwid.util import (MetaSuper, decompose_tagmarkup, calc_width,
  File "/Users/pankaj/work/code/github/pynput/.direnv/python-venv-3.7.3/lib/python3.7/site-packages/urwid/util.py", line 61, in <module>
    detected_encoding = detect_encoding()
  File "/Users/pankaj/work/code/github/pynput/.direnv/python-venv-3.7.3/lib/python3.7/site-packages/urwid/util.py", line 44, in detect_encoding
    initial = locale.getlocale()
  File "/Applications/Xcode.app/Contents/Developer/Library/Frameworks/Python3.framework/Versions/3.7/lib/python3.7/locale.py", line 587, in getlocale
    return _parse_localename(localename)
  File "/Applications/Xcode.app/Contents/Developer/Library/Frameworks/Python3.framework/Versions/3.7/lib/python3.7/locale.py", line 495, in _parse_localename
    raise ValueError('unknown locale: %s' % localename)
ValueError: unknown locale: UTF-8
```

**Comment by moses-palmer** [comment] 2019-12-24 16:51
Hmm, seems like am encoding issue on macOS... Does launching it with the environment variable LANG=C set help?

**Comment by jangid** [comment] 2019-12-24 18:48
Same result. I had set environment variable using

export LANG=C

The shell is zsh. But changing it to bash gave the same result.

**Comment by adutton** [comment] 2019-12-26 16:28
I am able to replicate this on a 12" MacBook without a touchbar.  I am running Catalina, though.
MacBook (Retina, 12-inch, Early 2015)
macOS Catalina 10.15.2 (19C57)

**Comment by moses-palmer** [comment] 2019-12-28 12:46
This might help with *pudb*: https://coderwall.com/p/-k_93g/mac-os-x-valueerror-unknown-locale-utf-8-in-python.

**Comment by Peter-Schorn** [comment] 2019-12-30 15:18
I have the exact same issues with the `a`, `s`, `t`, `y`, `x`, and `1` keys that pedrorrivero  mentioned. Also, If I hold down shift and press these keys (including the `1`) I the same media keys are registered.

**Comment by Peter-Schorn** [comment] 2019-12-30 15:21
Also, the media keys themselves are not registered at all. If I hold down fn and press the function keys, I get the correct name for each function key.

**Comment by LeLunZ** [comment] 2020-01-05 01:55
> This might help with _pudb_: https://coderwall.com/p/-k_93g/mac-os-x-valueerror-unknown-locale-utf-8-in-python.

Hey, I think I fixed the problem with the media keys. On my system everything is running perfectly!
Please check out my [pull request](https://github.com/moses-palmer/pynput/pull/214#issue-359263515)

**Comment by moses-palmer** [comment] 2020-01-06 09:11
@LeLunZ, thank you for your effort!

I have integrated your changes into the feature branch rather than merged the PR to simplify git history.

As soon as I get a report that it works, I will make a new release.

**Comment by moses-palmer** [comment] 2020-01-08 14:05
I have now released *pynput 1.6.5* with fixes for this issue.

**Comment by jangid** [comment] 2020-01-08 16:07
Working perfectly fine on macos 10.15.2. Thanks @moses-palmer @LeLunZ for your work.

**Comment by munsuri** [comment] 2020-01-20 11:09
I'm using pynput 1.6.5 tho, but the media keys are not working on Macbook pro 13" with touchbar.

**Comment by LeLunZ** [comment] 2020-01-20 14:38
> I'm using pynput 1.6.5 tho, but the media keys are not working on Macbook pro 13" with touchbar (not monitoring nor sending - vanilla Quarz sample works)

Which Mac OS version?
Btw. which vanilla quartz sample?

Could you debug the _darwin.py?

Would be interesting to know which values u have for vk and is_media in this line:
https://github.com/moses-palmer/pynput/blob/ef21d78316508f301e981da18479b8eea24f4319/lib/pynput/keyboard/_darwin.py#L287

Just set a breakpoint in the line and look at the values.

**Comment by munsuri** [comment] 2020-02-10 13:48
Sorry for the delay.

> Which Mac OS version?
> Btw. which vanilla quartz sample?
I'm currently in Mac OS X 10.14.6. The 'vanilla' quartz code sample can be found in one of the repo issues: https://github.com/moses-palmer/pynput/issues/190#issuecomment-551438603

> Could you debug the _darwin.py?
> Would be interesting to know which values u have for vk and is_media in this line:
> Just set a breakpoint in the line and look at the values.
The breakpoint is never reached for keys such as volume up, down, mute, brightness, etc...

**Comment by munsuri** [comment] 2020-02-12 10:09
Playing with the __darwin.py_ implementation and comparing the 'vanilla' Quartz sample, I found that sending media keys start working for me when adding  _result = result.CGEvent()_  (i.e. _ev.CGEvent()_) to the media key case.
```
        if self._is_media:
            result = getattr(
                    Quartz.NSEvent,
                    'otherEventWithType_'
                    'location_'
                    'modifierFlags_'
                    'timestamp_'
                    'windowNumber_'
                    'context_'
                    'subtype_'
                    'data1_'
                    'data2_')(
                NSSystemDefined,
                (0, 0),
                0xa00 if is_pressed else 0xb00,
                0,
                0,
                0,
                8,
                (self.vk << 16) | ((0xa if is_pressed else 0xb) << 8),
                -1)
+           result = result.CGEvent()
        else:
            result = Quartz.CGEventCreateKeyboardEvent(
                None, 0 if vk is None else vk, is_pressed)
```
I will check the key monitoring too...

**Comment by moses-palmer** [comment] 2020-02-12 11:25
@munsuri, thank you for your research! I will await any feedback on the listener case.

**Comment by LeLunZ** [comment] 2020-02-12 13:23
I will Test this in the evening (UTC+1)

**Comment by munsuri** [comment] 2020-02-12 16:39
So, regarding the listener case, it is not working because media keys type is NSSystemDefined, which is currently missing from the CGEventMaskBit events.

```
_EVENTS = (
        Quartz.CGEventMaskBit(Quartz.kCGEventKeyDown) |
        Quartz.CGEventMaskBit(Quartz.kCGEventKeyUp) |
        Quartz.CGEventMaskBit(Quartz.kCGEventFlagsChanged) |
 +      Quartz.CGEventMaskBit( NSSystemDefined )
)
```
Additionally, the same way media keys are differently constructed than normal keys in order to be sent, their received events also need to be processed differently than they are currently. That requires a few more code lines.

**Comment by munsuri** [comment] 2020-02-16 15:34
Created a pull request fixing both issues, the controller media key sending and listener: https://github.com/moses-palmer/pynput/pull/224

**Closed** 2020-02-28 08:02 UTC
