### ISSUE TITLE
MacOS keyboard listner error

### ISSUE THREAD

**Issue by myjulo** [moses-palmer/pynput#195] opened 2019-11-13 16:24 UTC
I've seen a couple of these issues posted here, but unfortunately they did not apply to my situation.

I have a 2099 Mac Pro/OSX El Capitan. I'm trying to run a code called "RTBox_light_demo.py" that can be downloaded from [this site](https://lobes.osu.edu/rt-box.php). It is used to communicate with a response box that is connected with USB, which can be used in psychophysics experiments (more details on the website linked before). I'm running the code within the PsychoPy app that is a python based app installed within the Anaconda environment.

It gives me the following error:

    Traceback (most recent call last):
    File "/Users/user/Downloads/RTBox_python_000/RTBox_light_demo.py", line 15, in <module>
        import RTBox
    File "/Users/user/Downloads/RTBox_python_000/RTBox.py", line 14, in <module>
        from pynput import keyboard
    File "/Users/user/anaconda3/envs/psypy3/lib/python3.6/site-packages/pynput/__init__.py", line 40, in <module>
        from . import keyboard
    File "/Users/user/anaconda3/envs/psypy3/lib/python3.6/site-packages/pynput/keyboard/__init__.py", line 40, in <module>
        from ._darwin import KeyCode, Key, Controller, Listener
    File "/Users/user/anaconda3/envs/psypy3/lib/python3.6/site-packages/pynput/keyboard/_darwin.py", line 144, in <module>
        class Listener(ListenerMixin, _base.Listener):
    File "/Users/user/anaconda3/envs/psypy3/lib/python3.6/site-packages/pynput/keyboard/_darwin.py", line 148, in Listener
        Quartz.CGEventMaskBit(Quartz.kCGEventKeyUp) |
    File "/Users/user/anaconda3/envs/psypy3/lib/python3.6/site-packages/objc/_lazyimport.py", line 181, in __getattr__
        raise AttributeError(name)
    AttributeError: CGEventMaskBit

I haven't had this error on my 2017 Macbook Pro/OSX Mojave. 

Any ideas on how to approach this error? Thank you!

**Edit**:
I've done some more testing and it comes down to that in the "RT_light_demo.py" first states:

    from psychopy import visual, event, core

And then states:

    import RTBox

If I remove `visual` from the first line, `from pynput import keyboard`does not give an error, but I obviously get other errors further down the script. If I import `visual` after I import `RTBox`, The script gets stuck at presenting the first visual presentation screen.

**Comment by moses-palmer** [comment] 2019-11-21 11:19
Given the stack trace and the workaround, I assume this issue is caused by incompatibilities in `pyobjc` unrelated to this project; thus I will close this issue. Please reopen if you think that this is incorrect.

**Closed by moses-palmer** 2019-11-21 11:19 UTC
