### ISSUE TITLE
Pynput crashes on openSUSE LEAP 15

### ISSUE THREAD

**Issue by TheLastProject** [moses-palmer/pynput#148] opened 2019-04-04 23:26 UTC
I believe this may be related to Wayland, although I have been told that LEAP 15 uses XWayland.

See https://github.com/Pext/Pext/issues/168 for more info.

Any way I can help debug this?

**Comment by moses-palmer** [comment] 2019-04-05 05:49
Thank you for your report.

Do you have more details, such as a stack trace?

As a side note, pynput in not very useful under XWayland, as interactions
seem to be limited to other applications running under XWayland.

**Comment by TheLastProject** [comment] 2019-04-05 19:10
The stack trace is in the linked issue, I'm pasting it here for completeness:

```
Traceback (most recent call last):
  File "/usr/lib/python3.6/site-packages/pext/__main__.py", line 62, in <module>
    from pynput import keyboard
  File "/usr/lib/python3.6/site-packages/pynput/__init__.py", line 40, in <module>
    from . import keyboard
  File "/usr/lib/python3.6/site-packages/pynput/keyboard/__init__.py", line 49, in <module>
    from ._xorg import KeyCode, Key, Controller, Listener
  File "/usr/lib/python3.6/site-packages/pynput/keyboard/_xorg.py", line 39, in <module>
    from pynput._util.xorg import (
  File "/usr/lib/python3.6/site-packages/pynput/_util/xorg.py", line 40, in <module>
    _check()
  File "/usr/lib/python3.6/site-packages/pynput/_util/xorg.py", line 38, in _check
    display = Xlib.display.Display()
  File "/usr/lib/python3.6/site-packages/Xlib/display.py", line 89, in __init__
    self.display = _BaseDisplay(display)
  File "/usr/lib/python3.6/site-packages/Xlib/display.py", line 71, in __init__
    protocol_display.Display.__init__(self, *args, **keys)
  File "/usr/lib/python3.6/site-packages/Xlib/protocol/display.py", line 160, in __init__
    raise error.DisplayConnectionError(self.display_name, r.reason)
Xlib.error.DisplayConnectionError: Can't connect to display ":0": b'No protocol specified\n'
```

**Comment by davidlares** [comment] 2020-03-06 20:20
This error is not only for OpenSUSE. I'm having the same issue on a Ubuntu machine as well, I'm using `virtualenv` with the 1.6.8 version.

**Comment by mohammedyunus009** [comment] 2020-06-02 16:52
Even im facing the same issue here (ubuntu 16) . Can anyone please suggest me to log long key press . Or any other module where i can log long key press . ? Thanks in advance

**Comment by moses-palmer** [comment] 2020-07-06 22:26
@TheLastProject, did you have a look at [this post](https://ubuntuforums.org/showthread.php?t=2290602)? This error could be caused by a bug in `python-xlib`, and is said to be solved by issuing `xhost +` in the terminal.

@davidlares, @mohammedyunus009, If your problem is running under _Wayland_, a possible solution would be to use the `uinput` backend. You will find more information [here](https://pynput.readthedocs.io/en/latest/index.html#forcing-a-specific-backend).

In any case, this appears to be a bug in a dependency with a known workaround, so I will close this issue.

**Closed by moses-palmer** 2020-07-06 22:26 UTC

**Comment by simotek** [comment] 2021-08-02 12:55
Can confirm the issue on openSUSE and the `xhost +` fix do you know of a bugreport in `python-xlib` so I can look at getting the fix?
