### ISSUE TITLE
creating keyboard listener on Xorg  with suppress=True too greedy

### ISSUE THREAD

**Issue by shark-low** [moses-palmer/pynput#273] opened 2020-06-05 14:16 UTC
When adding a "hotkey" to execute a function, I don't want that same hotkey to be echoed where it's been pressed. So I took a look into suppression but, with this code:

```python
from pynput import keyboard

current = set()
COMBINATIONS = [
    {keyboard.Key.shift, keyboard.KeyCode(char='p')},
    {keyboard.Key.shift, keyboard.KeyCode(char='P')}
]

def execute():
    print('honk honk\n')

def on_press(key):
    if any([key in COMBO for COMBO in COMBINATIONS]):
        current.add(key)
        if any(all(k in current for k in COMBO) for COMBO in COMBINATIONS):
            execute()

def on_release(key):
    if any([key in COMBO for COMBO in COMBINATIONS]):
        current.remove(key)

with keyboard.Listener(on_press=on_press, on_release=on_release, suppress=True) as listener:
    listener.join()
```

...the whole keyboard is grabbed. Meaning I can't type anything in any window, not even ctrl+c to break. I'm using i3 on .Org X Server 1.20.8 . 

I've seen issue #121 but it's not getting love anymore and I don't know how to reopen an issue like stated in there. Is there some way to suppress only the defined keys so they don't echo where they're pressed ?

**Comment by moses-palmer** [comment] 2020-07-06 22:57
Thank you for your report.

No, this is not possible under _X_. The attempt in [feature-xlib-suppress-select](https://github.com/moses-palmer/pynput/tree/feature-xlib-suppress-select) would allow you to suppress events for a specific window only, but not filtering on the actual events.

I will close this issue, as the code is unfortunately working as intended, albeit not as requested.

**Closed by moses-palmer** 2020-07-06 22:57 UTC
