### ISSUE TITLE
KeyError: <Key.ctrl_l: <162>> on windows

### ISSUE THREAD

**Issue by xiebruce** [moses-palmer/pynput#155] opened 2019-04-26 14:22 UTC
OS：`Windows 10` inside Parallels Desktop `14.1.2`，The host OS is macOS Mojave `10.14.4`, keyboard is Mac build in keyboard.
Python: `3.7.2`
Pynput: `1.4.2`

I set the key combination to `ctrl_l+shift+u`, when I press  `ctrl_l+shift+u`, it works fine, but when I press `option(alt)+shfit+u`(which I didn't set it as  key combination), it throw an error(but normal in win7):
```
2019-04-26 22:08:54,945: Unhandled exception in listener callback
Traceback (most recent call last):
  File "C:\Users\bruce\AppData\Local\Programs\Python\Python37\lib\site-packages\pynput\_util\__init__.py", line 157, in inner
    return f(self, *args, **kwargs)
  File "C:\Users\bruce\AppData\Local\Programs\Python\Python37\lib\site-packages\pynput\keyboard\_win32.py", line 243, in _process
    self.on_release(key)
  File "C:\Users\bruce\AppData\Local\Programs\Python\Python37\lib\site-packages\pynput\_util\__init__.py", line 78, in inner
    if f(*args) is False:
  File "D:\phpStudy\PHPTutorial\WWW\PicUploader\accessorys\PicUploaderHelper\PicUploaderHelper.pyw", line 187, in on_release
    current.remove(key)
KeyError: <Key.ctrl_l: <162>>
```

and another weird action is that after I press the key combination `ctrl_l+shift+u`, then I press `ctrl_l+shift`(without `u`), it acts just like I'm pressing `ctrl_l+shift+u`, I think it's a bug.

**Comment by moses-palmer** [comment] 2019-11-29 17:01
The exception is not raised in _pynput_ code, but rather in an attempt at removing a non-existing key from a _dict_.

Since the error happens outside of _pynput_, I will close this issue. If you think this is wrong, please provide a minimal working script to reproduce the error and reopen.

**Closed by moses-palmer** 2019-11-29 17:01 UTC
