### ISSUE TITLE
In the game,the analog keyboard is blocked.

### ISSUE THREAD

**Issue by jw-fu** [moses-palmer/pynput#316] opened 2020-10-15 11:13 UTC
I want to use pynput operate the League of heroes.But can't.

**Comment by moses-palmer** [comment] 2020-11-25 19:39
Thank you for your report.

This report, however, is a bit meagre. It does seem like a duplicate of #133, so I will close it. If that is not correct, please provide more information---at least a small script to reproduce the issue---and reopen.

**Closed by moses-palmer** 2020-11-25 19:39 UTC
