### ISSUE TITLE
AttributeError: 'NoneType' object has no attribute 'rsplit'

### ISSUE THREAD

**Issue by klint-k** [moses-palmer/pynput#296] opened 2020-08-05 06:37 UTC
pi@raspberrypi:~ $ python3
Python 3.7.3 ...
```
>>> from pynput import mouse
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 668, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 638, in _load_backward_compatible
  File "/usr/local/lib/python3.7/dist-packages/pynput-1.6.8-py3.7.egg/pynput/__init__.py", line 40, in <module>
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 668, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 638, in _load_backward_compatible
  File "/usr/local/lib/python3.7/dist-packages/pynput-1.6.8-py3.7.egg/pynput/keyboard/__init__.py", line 31, in <module>
  File "/usr/local/lib/python3.7/dist-packages/pynput-1.6.8-py3.7.egg/pynput/_util/__init__.py", line 55, in backend
AttributeError: 'NoneType' object has no attribute 'rsplit'
```
I just did a fresh install. Just copied and pasted from the instructions.

**Comment by moses-palmer** [comment] 2020-08-06 18:30
I think this is caused by `__package__` not being set for some reason. I have pushed a proposed fix to [fixup-backend-import](https://github.com/moses-palmer/pynput/tree/fixup-backend-import). Is it possible for you to test?

**Comment by klint-k** [comment] 2020-08-20 17:37
This is the install

```
~/Downloads/pynput $  sudo python3 setup.py install
running install
running bdist_egg
running egg_info
creating lib/pynput.egg-info
writing lib/pynput.egg-info/PKG-INFO
writing dependency_links to lib/pynput.egg-info/dependency_links.txt
writing requirements to lib/pynput.egg-info/requires.txt
writing top-level names to lib/pynput.egg-info/top_level.txt
writing manifest file 'lib/pynput.egg-info/SOURCES.txt'
reading manifest file 'lib/pynput.egg-info/SOURCES.txt'
writing manifest file 'lib/pynput.egg-info/SOURCES.txt'
installing library code to build/bdist.linux-armv7l/egg
running install_lib
running build_py
creating build
creating build/lib
creating build/lib/pynput
copying lib/pynput/__init__.py -> build/lib/pynput
copying lib/pynput/_info.py -> build/lib/pynput
creating build/lib/pynput/mouse
copying lib/pynput/mouse/_darwin.py -> build/lib/pynput/mouse
copying lib/pynput/mouse/__init__.py -> build/lib/pynput/mouse
copying lib/pynput/mouse/_dummy.py -> build/lib/pynput/mouse
copying lib/pynput/mouse/_xorg.py -> build/lib/pynput/mouse
copying lib/pynput/mouse/_base.py -> build/lib/pynput/mouse
copying lib/pynput/mouse/_win32.py -> build/lib/pynput/mouse
creating build/lib/pynput/keyboard
copying lib/pynput/keyboard/_darwin.py -> build/lib/pynput/keyboard
copying lib/pynput/keyboard/__init__.py -> build/lib/pynput/keyboard
copying lib/pynput/keyboard/_dummy.py -> build/lib/pynput/keyboard
copying lib/pynput/keyboard/_xorg.py -> build/lib/pynput/keyboard
copying lib/pynput/keyboard/_uinput.py -> build/lib/pynput/keyboard
copying lib/pynput/keyboard/_base.py -> build/lib/pynput/keyboard
copying lib/pynput/keyboard/_win32.py -> build/lib/pynput/keyboard
creating build/lib/pynput/_util
copying lib/pynput/_util/uinput.py -> build/lib/pynput/_util
copying lib/pynput/_util/__init__.py -> build/lib/pynput/_util
copying lib/pynput/_util/win32.py -> build/lib/pynput/_util
copying lib/pynput/_util/darwin.py -> build/lib/pynput/_util
copying lib/pynput/_util/xorg_keysyms.py -> build/lib/pynput/_util
copying lib/pynput/_util/win32_vks.py -> build/lib/pynput/_util
copying lib/pynput/_util/xorg.py -> build/lib/pynput/_util
creating build/bdist.linux-armv7l
creating build/bdist.linux-armv7l/egg
creating build/bdist.linux-armv7l/egg/pynput
creating build/bdist.linux-armv7l/egg/pynput/mouse
copying build/lib/pynput/mouse/_darwin.py -> build/bdist.linux-armv7l/egg/pynput/mouse
copying build/lib/pynput/mouse/__init__.py -> build/bdist.linux-armv7l/egg/pynput/mouse
copying build/lib/pynput/mouse/_dummy.py -> build/bdist.linux-armv7l/egg/pynput/mouse
copying build/lib/pynput/mouse/_xorg.py -> build/bdist.linux-armv7l/egg/pynput/mouse
copying build/lib/pynput/mouse/_base.py -> build/bdist.linux-armv7l/egg/pynput/mouse
copying build/lib/pynput/mouse/_win32.py -> build/bdist.linux-armv7l/egg/pynput/mouse
copying build/lib/pynput/__init__.py -> build/bdist.linux-armv7l/egg/pynput
copying build/lib/pynput/_info.py -> build/bdist.linux-armv7l/egg/pynput
creating build/bdist.linux-armv7l/egg/pynput/keyboard
copying build/lib/pynput/keyboard/_darwin.py -> build/bdist.linux-armv7l/egg/pynput/keyboard
copying build/lib/pynput/keyboard/__init__.py -> build/bdist.linux-armv7l/egg/pynput/keyboard
copying build/lib/pynput/keyboard/_dummy.py -> build/bdist.linux-armv7l/egg/pynput/keyboard
copying build/lib/pynput/keyboard/_xorg.py -> build/bdist.linux-armv7l/egg/pynput/keyboard
copying build/lib/pynput/keyboard/_uinput.py -> build/bdist.linux-armv7l/egg/pynput/keyboard
copying build/lib/pynput/keyboard/_base.py -> build/bdist.linux-armv7l/egg/pynput/keyboard
copying build/lib/pynput/keyboard/_win32.py -> build/bdist.linux-armv7l/egg/pynput/keyboard
creating build/bdist.linux-armv7l/egg/pynput/_util
copying build/lib/pynput/_util/uinput.py -> build/bdist.linux-armv7l/egg/pynput/_util
copying build/lib/pynput/_util/__init__.py -> build/bdist.linux-armv7l/egg/pynput/_util
copying build/lib/pynput/_util/win32.py -> build/bdist.linux-armv7l/egg/pynput/_util
copying build/lib/pynput/_util/darwin.py -> build/bdist.linux-armv7l/egg/pynput/_util
copying build/lib/pynput/_util/xorg_keysyms.py -> build/bdist.linux-armv7l/egg/pynput/_util
copying build/lib/pynput/_util/win32_vks.py -> build/bdist.linux-armv7l/egg/pynput/_util
copying build/lib/pynput/_util/xorg.py -> build/bdist.linux-armv7l/egg/pynput/_util
byte-compiling build/bdist.linux-armv7l/egg/pynput/mouse/_darwin.py to _darwin.cpython-37.pyc
byte-compiling build/bdist.linux-armv7l/egg/pynput/mouse/__init__.py to __init__.cpython-37.pyc
byte-compiling build/bdist.linux-armv7l/egg/pynput/mouse/_dummy.py to _dummy.cpython-37.pyc
byte-compiling build/bdist.linux-armv7l/egg/pynput/mouse/_xorg.py to _xorg.cpython-37.pyc
byte-compiling build/bdist.linux-armv7l/egg/pynput/mouse/_base.py to _base.cpython-37.pyc
byte-compiling build/bdist.linux-armv7l/egg/pynput/mouse/_win32.py to _win32.cpython-37.pyc
byte-compiling build/bdist.linux-armv7l/egg/pynput/__init__.py to __init__.cpython-37.pyc
byte-compiling build/bdist.linux-armv7l/egg/pynput/_info.py to _info.cpython-37.pyc
byte-compiling build/bdist.linux-armv7l/egg/pynput/keyboard/_darwin.py to _darwin.cpython-37.pyc
byte-compiling build/bdist.linux-armv7l/egg/pynput/keyboard/__init__.py to __init__.cpython-37.pyc
byte-compiling build/bdist.linux-armv7l/egg/pynput/keyboard/_dummy.py to _dummy.cpython-37.pyc
byte-compiling build/bdist.linux-armv7l/egg/pynput/keyboard/_xorg.py to _xorg.cpython-37.pyc
byte-compiling build/bdist.linux-armv7l/egg/pynput/keyboard/_uinput.py to _uinput.cpython-37.pyc
byte-compiling build/bdist.linux-armv7l/egg/pynput/keyboard/_base.py to _base.cpython-37.pyc
byte-compiling build/bdist.linux-armv7l/egg/pynput/keyboard/_win32.py to _win32.cpython-37.pyc
byte-compiling build/bdist.linux-armv7l/egg/pynput/_util/uinput.py to uinput.cpython-37.pyc
byte-compiling build/bdist.linux-armv7l/egg/pynput/_util/__init__.py to __init__.cpython-37.pyc
byte-compiling build/bdist.linux-armv7l/egg/pynput/_util/win32.py to win32.cpython-37.pyc
byte-compiling build/bdist.linux-armv7l/egg/pynput/_util/darwin.py to darwin.cpython-37.pyc
byte-compiling build/bdist.linux-armv7l/egg/pynput/_util/xorg_keysyms.py to xorg_keysyms.cpython-37.pyc
byte-compiling build/bdist.linux-armv7l/egg/pynput/_util/win32_vks.py to win32_vks.cpython-37.pyc
byte-compiling build/bdist.linux-armv7l/egg/pynput/_util/xorg.py to xorg.cpython-37.pyc
creating build/bdist.linux-armv7l/egg/EGG-INFO
copying lib/pynput.egg-info/PKG-INFO -> build/bdist.linux-armv7l/egg/EGG-INFO
copying lib/pynput.egg-info/SOURCES.txt -> build/bdist.linux-armv7l/egg/EGG-INFO
copying lib/pynput.egg-info/dependency_links.txt -> build/bdist.linux-armv7l/egg/EGG-INFO
copying lib/pynput.egg-info/requires.txt -> build/bdist.linux-armv7l/egg/EGG-INFO
copying lib/pynput.egg-info/top_level.txt -> build/bdist.linux-armv7l/egg/EGG-INFO
copying lib/pynput.egg-info/zip-safe -> build/bdist.linux-armv7l/egg/EGG-INFO
creating dist
creating 'dist/pynput-1.6.8-py3.7.egg' and adding 'build/bdist.linux-armv7l/egg' to it
removing 'build/bdist.linux-armv7l/egg' (and everything under it)
Processing pynput-1.6.8-py3.7.egg
Removing /usr/local/lib/python3.7/dist-packages/pynput-1.6.8-py3.7.egg
Copying pynput-1.6.8-py3.7.egg to /usr/local/lib/python3.7/dist-packages
pynput 1.6.8 is already the active version in easy-install.pth

Installed /usr/local/lib/python3.7/dist-packages/pynput-1.6.8-py3.7.egg
Processing dependencies for pynput==1.6.8
Searching for python-xlib==0.27
Best match: python-xlib 0.27
Processing python_xlib-0.27-py3.7.egg
python-xlib 0.27 is already the active version in easy-install.pth

Using /usr/local/lib/python3.7/dist-packages/python_xlib-0.27-py3.7.egg
Searching for evdev==1.3.0
Best match: evdev 1.3.0
Processing evdev-1.3.0-py3.7-linux-armv7l.egg
evdev 1.3.0 is already the active version in easy-install.pth

Using /usr/local/lib/python3.7/dist-packages/evdev-1.3.0-py3.7-linux-armv7l.egg
Searching for six==1.12.0
Best match: six 1.12.0
Adding six 1.12.0 to easy-install.pth file

Using /usr/lib/python3/dist-packages
Finished processing dependencies for pynput==1.6.8

```

This is the Result:
```
python3
Python 3.7.3 (default, Jul 25 2020, 13:03:44) 
[GCC 8.3.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> from pynput import mouse, keyboard
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 668, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 638, in _load_backward_compatible
  File "/usr/local/lib/python3.7/dist-packages/pynput-1.6.8-py3.7.egg/pynput/__init__.py", line 40, in <module>
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 668, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 638, in _load_backward_compatible
  File "/usr/local/lib/python3.7/dist-packages/pynput-1.6.8-py3.7.egg/pynput/keyboard/__init__.py", line 31, in <module>
  File "/usr/local/lib/python3.7/dist-packages/pynput-1.6.8-py3.7.egg/pynput/_util/__init__.py", line 55, in backend
AttributeError: 'NoneType' object has no attribute 'rsplit'

```

**Comment by moses-palmer** [comment] 2020-08-20 21:05
Just tio make sure---this is when installing from the branch I mentioned above? Line 29 of `lib/pynput/mouse/__init__.py` references `__name__`, not `__package__`?

**Comment by klint-k** [comment] 2020-08-21 00:05
Tried uninstall and reinstalled:

```
~/Downloads/pynput $ sudo python3 setup.py install --record files.txt
running install
running bdist_egg
running egg_info
writing lib/pynput.egg-info/PKG-INFO
writing dependency_links to lib/pynput.egg-info/dependency_links.txt
writing requirements to lib/pynput.egg-info/requires.txt
writing top-level names to lib/pynput.egg-info/top_level.txt
reading manifest file 'lib/pynput.egg-info/SOURCES.txt'
writing manifest file 'lib/pynput.egg-info/SOURCES.txt'
installing library code to build/bdist.linux-armv7l/egg
running install_lib
running build_py
creating build/bdist.linux-armv7l/egg
creating build/bdist.linux-armv7l/egg/pynput
creating build/bdist.linux-armv7l/egg/pynput/mouse
copying build/lib/pynput/mouse/_darwin.py -> build/bdist.linux-armv7l/egg/pynput/mouse
copying build/lib/pynput/mouse/__init__.py -> build/bdist.linux-armv7l/egg/pynput/mouse
copying build/lib/pynput/mouse/_dummy.py -> build/bdist.linux-armv7l/egg/pynput/mouse
copying build/lib/pynput/mouse/_xorg.py -> build/bdist.linux-armv7l/egg/pynput/mouse
copying build/lib/pynput/mouse/_base.py -> build/bdist.linux-armv7l/egg/pynput/mouse
copying build/lib/pynput/mouse/_win32.py -> build/bdist.linux-armv7l/egg/pynput/mouse
copying build/lib/pynput/__init__.py -> build/bdist.linux-armv7l/egg/pynput
copying build/lib/pynput/_info.py -> build/bdist.linux-armv7l/egg/pynput
creating build/bdist.linux-armv7l/egg/pynput/keyboard
copying build/lib/pynput/keyboard/_darwin.py -> build/bdist.linux-armv7l/egg/pynput/keyboard
copying build/lib/pynput/keyboard/__init__.py -> build/bdist.linux-armv7l/egg/pynput/keyboard
copying build/lib/pynput/keyboard/_dummy.py -> build/bdist.linux-armv7l/egg/pynput/keyboard
copying build/lib/pynput/keyboard/_xorg.py -> build/bdist.linux-armv7l/egg/pynput/keyboard
copying build/lib/pynput/keyboard/_uinput.py -> build/bdist.linux-armv7l/egg/pynput/keyboard
copying build/lib/pynput/keyboard/_base.py -> build/bdist.linux-armv7l/egg/pynput/keyboard
copying build/lib/pynput/keyboard/_win32.py -> build/bdist.linux-armv7l/egg/pynput/keyboard
creating build/bdist.linux-armv7l/egg/pynput/_util
copying build/lib/pynput/_util/uinput.py -> build/bdist.linux-armv7l/egg/pynput/_util
copying build/lib/pynput/_util/__init__.py -> build/bdist.linux-armv7l/egg/pynput/_util
copying build/lib/pynput/_util/win32.py -> build/bdist.linux-armv7l/egg/pynput/_util
copying build/lib/pynput/_util/darwin.py -> build/bdist.linux-armv7l/egg/pynput/_util
copying build/lib/pynput/_util/xorg_keysyms.py -> build/bdist.linux-armv7l/egg/pynput/_util
copying build/lib/pynput/_util/win32_vks.py -> build/bdist.linux-armv7l/egg/pynput/_util
copying build/lib/pynput/_util/xorg.py -> build/bdist.linux-armv7l/egg/pynput/_util
byte-compiling build/bdist.linux-armv7l/egg/pynput/mouse/_darwin.py to _darwin.cpython-37.pyc
byte-compiling build/bdist.linux-armv7l/egg/pynput/mouse/__init__.py to __init__.cpython-37.pyc
byte-compiling build/bdist.linux-armv7l/egg/pynput/mouse/_dummy.py to _dummy.cpython-37.pyc
byte-compiling build/bdist.linux-armv7l/egg/pynput/mouse/_xorg.py to _xorg.cpython-37.pyc
byte-compiling build/bdist.linux-armv7l/egg/pynput/mouse/_base.py to _base.cpython-37.pyc
byte-compiling build/bdist.linux-armv7l/egg/pynput/mouse/_win32.py to _win32.cpython-37.pyc
byte-compiling build/bdist.linux-armv7l/egg/pynput/__init__.py to __init__.cpython-37.pyc
byte-compiling build/bdist.linux-armv7l/egg/pynput/_info.py to _info.cpython-37.pyc
byte-compiling build/bdist.linux-armv7l/egg/pynput/keyboard/_darwin.py to _darwin.cpython-37.pyc
byte-compiling build/bdist.linux-armv7l/egg/pynput/keyboard/__init__.py to __init__.cpython-37.pyc
byte-compiling build/bdist.linux-armv7l/egg/pynput/keyboard/_dummy.py to _dummy.cpython-37.pyc
byte-compiling build/bdist.linux-armv7l/egg/pynput/keyboard/_xorg.py to _xorg.cpython-37.pyc
byte-compiling build/bdist.linux-armv7l/egg/pynput/keyboard/_uinput.py to _uinput.cpython-37.pyc
byte-compiling build/bdist.linux-armv7l/egg/pynput/keyboard/_base.py to _base.cpython-37.pyc
byte-compiling build/bdist.linux-armv7l/egg/pynput/keyboard/_win32.py to _win32.cpython-37.pyc
byte-compiling build/bdist.linux-armv7l/egg/pynput/_util/uinput.py to uinput.cpython-37.pyc
byte-compiling build/bdist.linux-armv7l/egg/pynput/_util/__init__.py to __init__.cpython-37.pyc
byte-compiling build/bdist.linux-armv7l/egg/pynput/_util/win32.py to win32.cpython-37.pyc
byte-compiling build/bdist.linux-armv7l/egg/pynput/_util/darwin.py to darwin.cpython-37.pyc
byte-compiling build/bdist.linux-armv7l/egg/pynput/_util/xorg_keysyms.py to xorg_keysyms.cpython-37.pyc
byte-compiling build/bdist.linux-armv7l/egg/pynput/_util/win32_vks.py to win32_vks.cpython-37.pyc
byte-compiling build/bdist.linux-armv7l/egg/pynput/_util/xorg.py to xorg.cpython-37.pyc
creating build/bdist.linux-armv7l/egg/EGG-INFO
copying lib/pynput.egg-info/PKG-INFO -> build/bdist.linux-armv7l/egg/EGG-INFO
copying lib/pynput.egg-info/SOURCES.txt -> build/bdist.linux-armv7l/egg/EGG-INFO
copying lib/pynput.egg-info/dependency_links.txt -> build/bdist.linux-armv7l/egg/EGG-INFO
copying lib/pynput.egg-info/requires.txt -> build/bdist.linux-armv7l/egg/EGG-INFO
copying lib/pynput.egg-info/top_level.txt -> build/bdist.linux-armv7l/egg/EGG-INFO
copying lib/pynput.egg-info/zip-safe -> build/bdist.linux-armv7l/egg/EGG-INFO
creating 'dist/pynput-1.6.8-py3.7.egg' and adding 'build/bdist.linux-armv7l/egg' to it
removing 'build/bdist.linux-armv7l/egg' (and everything under it)
Processing pynput-1.6.8-py3.7.egg
Copying pynput-1.6.8-py3.7.egg to /usr/local/lib/python3.7/dist-packages
Adding pynput 1.6.8 to easy-install.pth file

Installed /usr/local/lib/python3.7/dist-packages/pynput-1.6.8-py3.7.egg
Processing dependencies for pynput==1.6.8
Searching for python-xlib==0.27
Best match: python-xlib 0.27
Processing python_xlib-0.27-py3.7.egg
python-xlib 0.27 is already the active version in easy-install.pth

Using /usr/local/lib/python3.7/dist-packages/python_xlib-0.27-py3.7.egg
Searching for evdev==1.3.0
Best match: evdev 1.3.0
Processing evdev-1.3.0-py3.7-linux-armv7l.egg
evdev 1.3.0 is already the active version in easy-install.pth

Using /usr/local/lib/python3.7/dist-packages/evdev-1.3.0-py3.7-linux-armv7l.egg
Searching for six==1.12.0
Best match: six 1.12.0
Adding six 1.12.0 to easy-install.pth file

Using /usr/lib/python3/dist-packages
Finished processing dependencies for pynput==1.6.8
writing list of installed files to 'files.txt'


~/Downloads/pynput $ python3
Python 3.7.3 (default, Jul 25 2020, 13:03:44) 
[GCC 8.3.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> from pynput import mouse, keyboard
>>> 


```

**Comment by moses-palmer** [comment] 2020-08-30 19:08
It seems to work, so I will close this issue.

**Closed by moses-palmer** 2020-08-30 19:08 UTC
