### ISSUE TITLE
On mac, holding shift to type certain characters(like %) doesn't work

### ISSUE THREAD

**Issue by kevin132713** [moses-palmer/pynput#124] opened 2018-11-24 00:39 UTC
Sometimes holding shift works fine, like for all letters and :, but for others, like %, trying to type it(shift + 5 in this case) just types the original character and not the shifted version(5 in this case)

**Comment by moses-palmer** [comment] 2018-11-27 15:33
Duplicate of #83

**Closed by moses-palmer** 2018-11-27 15:33 UTC

**Comment by moses-palmer** [comment] 2021-10-20 13:26
#83 contains two separate issues, of which one is fixed. I will reopen this issue, since it contains only the remaining one.
