### ISSUE TITLE
Unable to capture  keys pressed inside a Remote Desktop Connection using pynput.

### ISSUE THREAD

**Issue by swadeeshs** [moses-palmer/pynput#263] opened 2020-05-15 09:06 UTC
I am trying to capture the keys pressed by the user when Remote Desktop Connection is opened. Is there a way to accomplish this?

**Comment by meaglerick** [comment] 2020-08-31 00:19
I was able to do this when my Remote Desktop session was not in Full Screen mode, additionally when using the new Windows Remote Desktop APP (not mstsc), it captures the keyboard input just fine.

**Comment by moses-palmer** [comment] 2020-08-31 15:01
In that case, I will close this issue as a workaround exists.

**Closed by moses-palmer** 2020-08-31 15:01 UTC

**Comment by walid-chekkouri** [comment] 2026-01-26 14:40
The issue is still occurring. I’m using the new Windows Remote Desktop app, and it requires the window to not be fully expanded, but for my special need I require it to be fully expanded, can this be fixed in Pynput @moses-palmer ?
