### ISSUE TITLE
Cannot enter password when screen locks

### ISSUE THREAD

**Issue by rustdesk** [moses-palmer/pynput#461] opened 2022-03-13 13:12 UTC
**Description**
Cannot enter password when screen locks. Looks like below get wrong focus input.
https://github.com/moses-palmer/pynput/blob/master/lib/pynput/keyboard/_xorg.py#L292

**Platform and pynput version**
Latest version, on Ubuntu 18, Fedora 28.

**To Reproduce**
Run below, then lock screen and go to password input window.

```
from pynput.keyboard import Controller
import time

keyboard = Controller()

while True:
  keyboard.press('A')
  keyboard.release('A')
  time.sleep(3)
```

**Comment by moses-palmer** [comment] 2022-04-01 21:37
Thank you for your report.

I will close this as a duplicate of #459.

**Closed by moses-palmer** 2022-04-01 21:37 UTC
