### ISSUE TITLE
How to properly control listener

### ISSUE THREAD

**Issue by masoudr** [moses-palmer/pynput#125] opened 2018-11-28 10:51 UTC
Hi,
I'm trying to add some control for keyboard.listner option. When I put an infinite loop after starting the listener I get all keys but when I press keys too fast it get some lags on printing the keys. When I put a very small delay in the loop problem is fixed but I can't do some key combinations like Alt+Shift, Ctrl+C, etc. I'm using Windows on python3.7 with v3.10.0.
Suppose this example:

```
from pynput import keyboard
from time import sleep

def on_press(key):
    try:
        k = key.char  # single-char keys
    except:
        k = key.name  # other keys
    print('Key pressed: ' + k)


lis = keyboard.Listener(on_press=on_press)
lis.start()

while True:
    # If I use pass I get some lags
    # If I put sleep combination keys doesn't work properly
    sleep(0.001)
    # pass
```
Thanks.

**Comment by moses-palmer** [comment] 2018-11-28 11:42
A listener is a [python thread](https://docs.python.org/3/library/threading.html#thread-objects). A busy wait is in almost all cases a bad idea.

Instead, use [join](https://docs.python.org/3/library/threading.html#threading.Thread.join):
```python
from pynput import keyboard
from time import sleep

def on_press(key):
    try:
        k = key.char  # single-char keys
    except:
        k = key.name  # other keys
    print('Key pressed: ' + k)


lis = keyboard.Listener(on_press=on_press)
lis.start()

lis.join()
```

**Comment by masoudr** [comment] 2018-11-28 11:53
Thanks, but I didn't solve my problem. How about making listener non-blocking?

**Comment by moses-palmer** [comment] 2018-11-28 11:59
It is non-blocking---that is why it is running in a separate thread. If you have other logic keeping your program running, just omit the call to `join`.

**Comment by moses-palmer** [comment] 2018-11-28 12:04
What issue do you experience when using the *join suggestion*?

**Comment by masoudr** [comment] 2018-11-28 19:49
If I use the `join` it works OK but some key combinations like `Alt+Shift` don't act well and I should press it 3 times or so to change the language. If I use an infinite loop after calling `start` I don't have this problem but I get a bad input lag.

**Comment by moses-palmer** [comment] 2019-12-04 08:21
The issue with the listener interfering with the system is supposedly resolved on the _master_ branch. Is it possible for you to test?

**Comment by masoudr** [comment] 2019-12-04 09:34
I can't quite remember how it was. But I've tested the above code but with using an infinite loop (without delay) it still gets some small latency to respond, on the other hand, it seems that the problem with using key combinations has been solved.

**Comment by moses-palmer** [comment] 2019-12-04 12:58
Thank you for your quick response!

In that case, I will close this issue, as I am fairly confident that the latency is caused by the busy loop.

**Closed by moses-palmer** 2019-12-04 12:58 UTC
