### ISSUE TITLE
'GlobalHotKeys' object has no attribute '_event_filter' (Windows 7 x64)

### ISSUE THREAD

**Issue by d-01** [moses-palmer/pynput#200] opened 2019-12-12 12:57 UTC
pynput version: 1.6.0
Python 3.7.5 (x32)
Windows 7 (x64)

Example taken from docs unmodified (https://pynput.readthedocs.io/en/latest/keyboard.html#global-hotkeys)

```python
from pynput import keyboard

def on_activate_h():
    print('<ctrl>+<alt>+h pressed')

def on_activate_i():
    print('<ctrl>+<alt>+i pressed')

with keyboard.GlobalHotKeys({
        '<ctrl>+<alt>+h': on_activate_h,
        '<ctrl>+<alt>+i': on_activate_i}) as h:
    h.join()
```

After script run any key press leads to an error:

```
Unhandled exception in listener callback
Traceback (most recent call last):
  File "C:\python\lib\site-packages\pynput\_util\__init__.py", line 162, in inner
    return f(self, *args, **kwargs)
  File "C:\python\lib\site-packages\pynput\_util\win32.py", line 382, in _handler
    converted = self._convert(code, msg, lpdata)
  File "C:\python\lib\site-packages\pynput\keyboard\_win32.py", line 244, in _convert
    if self._event_filter(msg, data) is False:
AttributeError: 'GlobalHotKeys' object has no attribute '_event_filter'
Traceback (most recent call last):
  File "demo-pynput-test.py", line 13, in <module>
    h.join()
  File "C:\python\lib\site-packages\pynput\_util\__init__.py", line 210, in join
    six.reraise(exc_type, exc_value, exc_traceback)
  File "C:\python\lib\site-packages\six.py", line 692, in reraise
    raise value.with_traceback(tb)
  File "C:\python\lib\site-packages\pynput\_util\__init__.py", line 162, in inner
    return f(self, *args, **kwargs)
  File "C:\python\lib\site-packages\pynput\_util\win32.py", line 382, in _handler
    converted = self._convert(code, msg, lpdata)
  File "C:\python\lib\site-packages\pynput\keyboard\_win32.py", line 244, in _convert
    if self._event_filter(msg, data) is False:
AttributeError: 'GlobalHotKeys' object has no attribute '_event_filter'
```

**Comment by moses-palmer** [comment] 2019-12-12 18:51
Thank you for your report.

Yes, this is caused by an incorrect call to `super` in `GlobalHotKeys`; I only tested it under _Xorg_, and assumed it would work on other platforms since it built on platform independent code.

When investigating, I realised that fixing the call is unfortunately not enough; the virtual key code send on Windows is modified when <kbd>ctrl+alt</kbd> are pressed, and will thus not match the hot keys.

I will investigate further.

**Comment by moses-palmer** [comment] 2019-12-18 20:30
I have pushed a branch that fixes the issue: [fixup-win32-hotkeys](https://github.com/moses-palmer/pynput/tree/fixup-win32-hotkeys).

This branch fixes the following issues:
* The `GlobalHotKeys` constructor incorrectly called its super constructor, leading to a crash on Windows specifically.
* The keyboard events delivered to the global hotkey listener on Windows were affected by modifier keys, leading to no hotkey matches.

If you find the time, please test this branch and report any issues.

**Comment by moses-palmer** [comment] 2019-12-19 20:07
This branch has been merged into master, so I will close this issue.

**Closed by moses-palmer** 2019-12-19 20:07 UTC
