### ISSUE TITLE
Auto detect key on mouse double clicks

### ISSUE THREAD

**Issue by masoudr** [moses-palmer/pynput#51] opened 2017-09-23 06:12 UTC
Hi,
I have a strange problem I wrote a simple script to show the current key char or key name and I detect the `ctrl+c` function. It works fine if I press `ctrl+c` but when I double click on a file it accidentally detects the `ctrl+c` but I never pressed any key on my keyboard and only double click my mouse.
Here is the code I used:

```
from pynput import keyboard
from time import sleep
import pyperclip

def on_press(key):
    if key == keyboard.Key.esc:
        listener.stop()
    else:
        try:
            print("key.char", ord(key.char))
            if(ord(key.char) == 3):
                print("Ctrl+C Pressed!!!")
        except:
            print("key.name", key.name)

lis = keyboard.Listener(on_press=on_press)
print("start #1")
lis.start()
sleep(100)
```
I didn't use `lis.join()` because I'm creating an object from this code and don't want to make it block my code.

I am not sure if this problem relates to your library but is there any way to detect `ctrl+c` maybe it won't duplicate.
Thanks.

**Comment by moses-palmer** [comment] 2018-01-12 20:36
Sorry for the very late reply.

If I modify your example thus:
```python
from pynput import keyboard                   
from time import sleep 


def on_press(key):     
    if key == keyboard.Key.esc:               
        lis.stop()     
    else:              
        try:           
            print("key.char", ord(key.char))  
            if(ord(key.char) == 3):           
                print("Ctrl+C Pressed!!!")    
        except:        
            print("key.name", key.name)       


lis = keyboard.Listener(on_press=on_press)    
print("start #1")      
lis.start()            
sleep(100)
```

...run it and then double click on a file, nothing extraordinary happens. On what platform does this occur?

If you want to detect `'c'`, by the way, you may want to compare `key.char` directly against `'c'` (`ord('c') == 99`).

**Comment by masoudr** [comment] 2018-01-13 18:00
@moses-palmer I'm using windows, I need to detect `Ctrl+C`. I think when I double click `ord(key.char)` gets equal to 3. I don't know why this happening.

**Comment by moses-palmer** [comment] 2018-02-27 19:44
I'm closing this issue, as I cannot reproduce it. Does the code sample I posted above cause the issue for you?

**Closed by moses-palmer** 2018-02-27 19:44 UTC

**Comment by masoudr** [comment] 2018-02-28 05:42
@moses-palmer It seems that the problem was related to a windows issue, not the module itself. I haven't faced this issue for a long time. Thanks by the way.
