### ISSUE TITLE
install (via setup.py or pip) failing because of xlib

### ISSUE THREAD

**Issue by gilou** [moses-palmer/pynput#76] opened 2018-02-20 19:28 UTC
Hi,
When installing with pip3 on Ubuntu 16.04, I get an error : 
`Invalid requirement: 'python-xlib>=0.17; linux in "sys_platform"'`
So I cloned the repo, and try to run the setup myself, got:

```
Searching for python-xlib>=0.17
Reading https://pypi.python.org/simple/python-xlib/
Best match: python-xlib 0.21
Downloading https://pypi.python.org/packages/eb/de/b0eaaea7b8512dc41504db071824eef30293ff55c58d83081ebaebe85a38/python-xlib-0.21.tar.bz2#md5=cdf342aa145c2be0ccae46cfb7b62551
Processing python-xlib-0.21.tar.bz2
Writing /tmp/easy_install-91h9j2ig/python-xlib-0.21/setup.cfg
Running python-xlib-0.21/setup.py -q bdist_egg --dist-dir /tmp/easy_install-91h9j2ig/python-xlib-0.21/egg-dist-tmp-l9e7uftz
zip_safe flag not set; analyzing archive contents...
Moving UNKNOWN-0.0.0-py3.5.egg to /usr/local/lib/python3.5/dist-packages
Adding UNKNOWN 0.0.0 to easy-install.pth file

Installed /usr/local/lib/python3.5/dist-packages/UNKNOWN-0.0.0-py3.5.egg
error: The 'python-xlib>=0.17' distribution was not found and is required by pynput

```

The lib seems to be named xlib only (but maybe python3-xlib would have cut it), so I edited the setup to change the dependency, and it worked.

So maybe just setting xlib instead of python-xlib would make it OK for both versions? (as it's a reasonnable requirement in both pip2 & pip3) ?

**Comment by gilou** [comment] 2018-02-20 19:34
seems the issue arises also with Python2

**Comment by moses-palmer** [comment] 2018-02-26 20:01
I routinely reinstall _pynput_ in _virtualenvs_, and I have never experienced this. What version of _pip_ and _setuptools_ do you use? When I run `python -c 'import pip, setuptools; print(pip.__version__, setuptools.__version__)'`, I get the output `9.0.1 38.5.1`

**Comment by gilou** [comment] 2018-02-28 11:18
This was done on a machine yielding this:
```
% python -c 'import pip, setuptools; print(pip.__version__, setuptools.__version__)'
('8.1.1', '20.7.0')
% python3 -c 'import pip, setuptools; print(pip.__version__, setuptools.__version__)'
8.1.1 24.0.2

```

**Comment by moses-palmer** [comment] 2018-04-04 20:48
Did you find out the cause of this? Do you think it could have been a temporary glitch with *PyPi* or the *python-xlib* package? Your installation log seems to suggest this:

    Moving UNKNOWN-0.0.0-py3.5.egg to /usr/local/lib/python3.5/dist-packages
    Adding UNKNOWN 0.0.0 to easy-install.pth file

I am going to close this issue. Please reopen if it persists.

**Closed by moses-palmer** 2018-04-04 20:48 UTC
