### ISSUE TITLE
InvalidCharacterException

### ISSUE THREAD

**Issue by kyzrong** [moses-palmer/pynput#299] opened 2020-08-24 01:14 UTC
in centos7x64 python3.6

```
#coding:utf-8
import pynput
pynput.keyboard.Controller().type('中文')
```

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python3.6/site-packages/pynput/keyboard/_base.py", line 468, in type
    raise self.InvalidCharacterException(i, character)
pynput.keyboard._base.InvalidCharacterException: (0, '中')

the code run well in windows10,is there any solution?
thank you!

**Comment by gdiShun** [comment] 2020-08-24 04:51
Appears to be the same or a similar issues as [this one](https://github.com/moses-palmer/pynput/issues/94), which I posted some more information on around the same time as this was created.

**Comment by moses-palmer** [comment] 2020-08-24 20:57
Yes, this is a duplicate of #94. I will close this issue.

**Closed by moses-palmer** 2020-08-24 20:57 UTC

**Comment by kyzrong** [comment] 2020-08-25 03:36
If want to output chinese with pynput , must verify each chinese word in this file:
"/usr/local/lib/python3.6/site-packages/pynput/_util/xorg_keysyms.py"

with this code you will get all the chinese word with unicode:

```
with open('chineseSyms.txt','w') as f:
	for i in range(19968,40869):
		hexString = hex(i)
		line = '    \'theCn\':('+str(hexString)+',u\'\\u'+hexString[-4:]+'\'),'
		theChinese = hexString.replace('0x','\\u').encode('utf-8').decode('unicode_escape')
		line = line.replace('theCn',theChinese)
		f.write(line)
		f.write('\n')
```
then add the content to xorg_keysyms.py.
like this:

```
    'zacute': (0x01bc, u'\u017A'),
    'zcaron': (0x01be, u'\u017E'),
    'zerosubscript': (0x1002080, u'\u2080'),
    'zerosuperior': (0x1002070, u'\u2070'),
    'zstroke': (0x10001b6, u'\u01B6'),
    '一':(0x4e00,u'\u4e00'),
    '丁':(0x4e01,u'\u4e01'),
    '丂':(0x4e02,u'\u4e02'),
    '七':(0x4e03,u'\u4e03'),
    '丄':(0x4e04,u'\u4e04'),
    '丅':(0x4e05,u'\u4e05'),
```
