### ISSUE TITLE
Weird timing of the Listener.join() method

### ISSUE THREAD

**Issue by TheoRet** [moses-palmer/pynput#75] opened 2018-02-20 19:11 UTC
Hello, I am using Linux Mint 18. 

While the last two issues I posted are minor problems, this bug creates big trouble in my application.

I can reproduce it with the following code:
```
from pynput import keyboard
from threading import Thread
import time

x=keyboard.Listener()
x.start()
def f(x):
    time.sleep(1)
    x.stop()
    print("stopped")
Thread(target=f,args=(x,)).start()
x.join()
print("joined")
```

What should happen is that after the delay of 1sec, "stopped" and "joined" is printed.

What actually happens:
- After 1sec delay, "stopped" is printed, but not "joined".
- "joined" only prints when I press any key after "stopped" has already appeared.

**Comment by moses-palmer** [comment] 2018-02-26 21:08
Thank you for your report.

It does appear that stop does not forcefully stop the listener. I have not noticed before, since all unit tests end with a requirement to press _Enter_.

I will look into it; the _1.4_ release does not seem to get any nearer ;-)

**Comment by moses-palmer** [comment] 2018-04-04 20:45
I have pushed a fix to *master*.

It was caused by three small issues that together caused the call to `join` to block.

**Closed by moses-palmer** 2018-04-04 20:45 UTC
