### ISSUE TITLE
mouse.Controller().scroll(dx,dy) is not work

### ISSUE THREAD

**Issue by DOCCA0** [moses-palmer/pynput#222] opened 2020-02-11 05:57 UTC
mouse.Controller().scroll(dx,dy)is not work
I just use mouse.Listener to record the actions of my mouse,then I store it as *.txt.And I read the txt to let it act.
mouse.Controller().press() and mouse.Controller().release() work well,but when it runs mouse.Controller().scroll(dx,dy),there is almost no action.

**Comment by moses-palmer** [comment] 2020-02-12 11:40
Thank you for your report.

On what platform do you run *pynput*? Could you please provide a small code example exhibiting the issue?

Depending on the platform, the handling of the arguments differs, and I would not be surprised if passing values from events to the controller does not yield the expected result.

**Comment by DOCCA0** [comment] 2020-02-13 09:17
in mouse.Controller().scroll(dx,dy), dx and dy need  values of pixels,  therefore I tried pyautogui and win32api, they all need pixel values,but in pynput.mouse(scroll=scroll(x,y,dx,dy)) ,dx and dy is not a pixel value

**Comment by moses-palmer** [comment] 2020-02-13 09:30
Since you tried `win32api`, I assume you run this on _Windows_.

When inspecting the code, I notice that the transformation of the event data performed by the listener is not performed by the controller. I think this might be the cause of the issue you are experiencing. I will look into it later today and get back to you.

**Comment by DOCCA0** [comment] 2020-02-13 09:36
yes,it is the point that  the transformation of the event data performed by the listener is not performed by the controller.After many attempts, I did not find a package to solve my prob.Thx!

**Comment by moses-palmer** [comment] 2020-02-17 16:38
I have merged a fix into *master*.

**Closed by moses-palmer** 2020-02-17 16:38 UTC
