### ISSUE TITLE
Sending modifier keys on OSX does not work

### ISSUE THREAD

**Issue by radixcl** [moses-palmer/pynput#65] opened 2018-01-12 17:09 UTC
Hi,

I'm having problems sending modifier keys on OSX high sierra, I don't know if the issue is also present on prior versions of OSX.

This piece of code does not work on OSX, the result is "a", should be "A".
```python
with keyboard.pressed(Key.shift):
    keyboard.press('a')
    keyboard.release('a')
```

On Windows that works flawlessly.

Thank you

**Comment by moses-palmer** [comment] 2018-01-12 18:33
Thank you for report!

I can confirm that it does not work older versions either, such as _El Capitan_. I have made a new release (_1.3.9_) which fixes the issue for me.

The problem was actually not related to modifiers, but the single character that you are trying to type: _A_. An incorrect comparison interpreted this as the absence of an actual virtual key code, and made a fallback to typing a unicode character, with the side effect that the shift state was ignored.

I will close this issue. Please reopen if you still encounter issues.

**Closed by moses-palmer** 2018-01-12 18:33 UTC
