### ISSUE TITLE
Problem to make work in Raspberry Pi (Python 2.7.9)

### ISSUE THREAD

**Issue by SrBrahma** [moses-palmer/pynput#48] opened 2017-09-07 00:32 UTC
Hello, I was looking a package to get keypresses from the user for my Raspberry Pi (the last august release) project, and I found this package. I don't understand too much about python packages installation, but I proceed in this way:

"sudo pip install pynput"

In my code, I just inserted on the top "import pynput", and I started having trouble.

First I got errors of missing the "six" package, so I did:

"sudo pip install --upgrade six"

The --upgrade was needed. But now, I have a new problem:

"Traceback (most recent call last):
  File "pdaGraphics.py", line 8, in <module>
    import pynput
  File "/usr/local/lib/python2.7/dist-packages/pynput/__init__.py", line 23, in <module>
    from . import keyboard
  File "/usr/local/lib/python2.7/dist-packages/pynput/keyboard/__init__.py", line 49, in <module>
    from ._xorg import KeyCode, Key, Controller, Listener
  File "/usr/local/lib/python2.7/dist-packages/pynput/keyboard/_xorg.py", line 38, in <module>
    from pynput._util.xorg import (
  File "/usr/local/lib/python2.7/dist-packages/pynput/_util/xorg.py", line 38, in <module>
    _check()
  File "/usr/local/lib/python2.7/dist-packages/pynput/_util/xorg.py", line 36, in _check
    display = Xlib.display.Display()
  File "/usr/local/lib/python2.7/dist-packages/Xlib/display.py", line 127, in __init__
    mod.init(self, info)
  File "/usr/local/lib/python2.7/dist-packages/Xlib/ext/xinput.py", line 652, in init
    disp.ge_add_event_data(info.major_opcode, device_event, DeviceEventData)
  File "/usr/local/lib/python2.7/dist-packages/Xlib/display.py", line 227, in __getattr__
    raise AttributeError(attr)
AttributeError: ge_add_event_data"

I don't know what to do here.
Already tried some commands like "sudo apt-get install python-xlib", but still no results.

**Comment by moses-palmer** [comment] 2017-09-17 13:29
Sorry for the late reply.

I have tested installing *pynput* in a *Debian* docker container as follows:
```bash
user@host:~$ docker run -ti --rm -e DISPLAY=:1 -v /tmp/.X11-unix:/tmp/.X11-unix debian

root@docker:~$ apt update && apt install python-pip && pip install pynput
root@docker:~$ python -c 'import pynput; pynput.mouse.Controller().position = (5, 5)'
```
This works. I get no errors about *six* missing, and no startup errors from *python-xlib*.

My suggestion is to first purge all installed packages and reinstall them as your user, and then to ensure that *python-xlib* is up-to-date.

**Comment by moses-palmer** [comment] 2018-01-12 20:37
Did you solve this problem? I will close this issue now, but please reopen it if the problem remains.

**Comment by alexeinemkov** [comment] 2019-12-05 21:31
Hello!
The problem is similar to the one described in this issue, but there is python 2.7, and I have 3.7 and RPI4.
When I installed the package with: 
```
pip install pynput
 pip3 install pynput
```
I got the following errors:
```
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/dist-packages/pynput/keyboard/_xorg.py", line 85, in _from_symbol
    **kwargs)
  File "/usr/local/lib/python3.7/dist-packages/pynput/keyboard/_base.py", line 131, in from_vk
    return cls(vk=vk, **kwargs)
  File "/usr/local/lib/python3.7/dist-packages/pynput/keyboard/_base.py", line 62, in __init__
    raise ValueError(kwargs)
ValueError: {'is_media': True}

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "MyScript.py", line 10, in <module>
    import pynput
  File "/usr/local/lib/python3.7/dist-packages/pynput/__init__.py", line 40, in <module>
    from . import keyboard
  File "/usr/local/lib/python3.7/dist-packages/pynput/keyboard/__init__.py", line 49, in <module>
    from ._xorg import KeyCode, Key, Controller, Listener
  File "/usr/local/lib/python3.7/dist-packages/pynput/keyboard/_xorg.py", line 105, in <module>
    class Key(enum.Enum):
  File "/usr/local/lib/python3.7/dist-packages/pynput/keyboard/_xorg.py", line 156, in Key
    media_play_pause = KeyCode._from_media('Play')
  File "/usr/local/lib/python3.7/dist-packages/pynput/keyboard/_xorg.py", line 102, in _from_media
    return cls._from_symbol('XF86Audio' + name, is_media=True, **kwargs)
  File "/usr/local/lib/python3.7/dist-packages/pynput/keyboard/_xorg.py", line 90, in _from_symbol
    **kwargs)
  File "/usr/local/lib/python3.7/dist-packages/pynput/keyboard/_base.py", line 131, in from_vk
    return cls(vk=vk, **kwargs)
  File "/usr/local/lib/python3.7/dist-packages/pynput/keyboard/_base.py", line 62, in __init__
    raise ValueError(kwargs)
ValueError: {'is_media': True}
```

It turned out that the rpi4  using pynput==1.5.0. When I installed version 1.4.5 the problem was solved.

**Comment by moses-palmer** [comment] 2019-12-06 07:20
Thank you for your report.

The introduction of experimental support for media keys in _pynput 1.5.0_ unfortunately broke two of the three supported backends. I have pushed fixes for _macOS_ and _Xorg_; can you test with _pynput 1.5.2_?

**Comment by alexeinemkov** [comment] 2019-12-06 10:15
I installed version 1.5.2.  It's okay, it's working. Thanks!

**Closed** 2019-12-06 10:17 UTC
