### ISSUE TITLE
Middle button of a mouse cannot be released

### ISSUE THREAD

**Issue by gh0styxx** [moses-palmer/pynput#474] opened 2022-05-28 21:11 UTC
**Description**
If I want to perform an action while clicking the middle button on my mouse (scroll button, but I click it, not scroll) the action is performed once. When I release the button, the action is performed once again, because when I release the middle button it is known as pressing. I have the same issue with using another buttons on my mouse, like Button.left or Button.right.
If I try to perform the same function using a key on the keyboard, the pressing and releasing the button works like it should, the action is performed only once.

**Platform and pynput version**
I use MacOS 12.3 Monterey and pynput 1.7.6

**To Reproduce**
```
def on_click(x, y, button, pressed):
    btn = button.name
    if (btn == 'middle'):
        my_function()

mouse_listener = MouseListener(on_click=on_click)
mouse_listener.start()
mouse_listener.join()
```
If physically click middle button once and release it, the code under "my_function" will perform twice.

**Comment by moses-palmer** [comment] 2022-06-19 16:33
Thank you for your report.

Have you tried calling `my_function` only when `pressed` is `True`? The `on_click` callback will be triggered when a button is pressed as well as released.

I do not think this is caused by a bug in this library, so I will close this issue. If you think otherwise, please reopen.

**Closed by moses-palmer** 2022-06-19 16:33 UTC

**Comment by gh0styxx** [comment] 2022-06-20 13:00
Thank you, I missed this variable. it helps to solve my problem. Thanks!
