### ISSUE TITLE
Ignoring capslock and shift key Windows 10/

### ISSUE THREAD

**Issue by dcxxx** [moses-palmer/pynput#139] opened 2019-03-12 19:50 UTC
When  I type a visible character, the KeyCode char delivered to the callback routine does not reflect the state of the Shift or Caps Lock keys.  It reflects the state of Caps Lock when I started the program.  

I have traced this down to the self._GetKeyboardState(ctypes.byref(self.__state)) call in the  _util\win32.py module.  Windows always returns the exact same value for the KeyBoard State vector.  I believe this is related to the fact that GetKeyBoard state appears to peek at the queue and not remove it, but I don't consider myself to have much expertise in Windows keyboard handling.  In the attached file, I have put a  fix which does a  Windows_GetKeyState(1) call, just before the ._GetKeyboardState() call. This appears to cure the problem.  Not being familiar with how the Windows keyboard message queue operates, I'm not really sure if this call should be before or after the existing call, or if I am on the wrong track.

[win32.py.txt](https://github.com/moses-palmer/pynput/files/2958531/win32.py.txt)

**Comment by SpecialCharacter** [comment] 2019-03-14 21:53
I have the same issue: Shift-a will give "A" on the screen, but "a" in the memory.
It is possible to fix that for letters by establishing a variable on the shift key and .capitalize() the letter when shift is pressed.
However, this will fail with punctuation etc.
Any help how to fix this?

**Comment by dcxxx** [comment] 2019-03-15 13:08
If you look at my previous post, you will see an attached file called win32.py.txt.   Rename it to get rid of the .txt extension.  If you replace that file in the library distribution (..\Python37\Lib\site-packages\pynput\_util\win32.py, where .. is the root of wherever Python is installed on your system).  I believe it will solve your problem.  Please note that I have not tested this very extensively and I am not completely sure how the Windows keyboard message queues work so it might have some side effect I haven't yet noticed.  Please let me know if it resolves your problem.

**Comment by SpecialCharacter** [comment] 2019-03-15 23:17
Thanks, I already took a look on your .py file :)
The problem is that I want to ultimately use my file on a Mac, so Windows keyboard handling won't do any good for me...
Just out of curiosity, does your file work with punctuation?

**Comment by SpecialCharacter** [comment] 2019-03-17 11:14
Update: Regarding "establishing a variable on the shift key", I noticed that it is too fast: While it is "A" in the output, it is "a" in the memory. Does anybody know how to slow it down so it matches the characteristics of the Shift key on the physical keyboard?

**Comment by moses-palmer** [comment] 2019-11-29 07:39
Since this appears to be related to #118 and other issues relating to the shift state, I will close this issue.

**Closed by moses-palmer** 2019-11-29 07:39 UTC
