### ISSUE TITLE
deadkeys

### ISSUE THREAD

**Issue by SpecialCharacter** [moses-palmer/pynput#42] opened 2017-08-18 20:56 UTC
The deadkeys are still not working 100% correctly, I think.

Let's say I want to turn `M into M̀ (a combined character). 
But that does not function because there is no character M̀ (at least not in my keyboard layout), so the deadkey remains virtual, until I type a second character (which is ignored in the memory) and the deadkey appears on my screen together with the second character.

I don't know if there is a way to fix this. 
What I want to have is the second character not being ignored in the memory.

Also, when I type the deadkey twice, while on my screen the characters are `` (down, down), they are ´` (up, down) in the memory.
I think that is odd...

**Comment by logileifs** [comment] 2017-08-18 21:46
Yeah is there any way to detect when user pressed a deadkey to possibly be composing a combined character? We have a lot of those in Icelandic and none seem to work, so far I've tried `áíóéýú` with no luck

**Comment by logileifs** [comment] 2017-08-18 21:54
Okay I just figured out I can use `KeyCode.from_dead('`').join(KeyCode.from_char('e'))` to combine deadkeys with others and create a combined character but they don't show up right. They show up as grave (è) when they should show up as acute (é). Is there any way around this ?

**Comment by moses-palmer** [comment] 2017-08-18 22:06
Thank you for your report.

I will look into the issue with disappearing second characters shortly.

@logileifs Did you paste the code correctly? You seem to be joining a grave accent (`) with an e, which should indeed produce è.

**Comment by logileifs** [comment] 2017-08-18 23:24
Silly mistake of me, you're absolutely right, I was using the wrong one. One question though, does pynput provide any information on when a dead key is pressed? Or is it just treated as any other alphanumeric character?

**Comment by SpecialCharacter** [comment] 2017-08-18 23:54
Logileifs, can you show me how exactly to use KeyCode.from_dead?
I probably need it in an if ... then structure.

**Comment by logileifs** [comment] 2017-08-19 00:00
@SpecialCharacter just exactly like I posted in the comment above. You put your dead key in `from_dead` and your combining key in `from_char`.  So to produce an è you would do ```KeyCode.from_dead('`').join(KeyCode.from_char('e'))```

**Comment by SpecialCharacter** [comment] 2017-08-19 00:19
The problem is that I need something like

    if key.char == 'M':
            elif memory[-2:-1] == '`':
                KeyCode.from_dead('`').join(KeyCode.from_char('M'))

But how do I print it? I suppose with keyboard.type?

**Comment by logileifs** [comment] 2017-08-19 10:09
`KeyCode.from_dead('`').join(KeyCode.from_char('M'))` returns a pynput KeyCode object which but you can access its character with `.char`. So something like this should work:

```ḿ = KeyCode.from_dead('`').join(KeyCode.from_char('M'))
print(ḿ.char)```

**Comment by SpecialCharacter** [comment] 2017-08-19 10:54
@logileifs it does not work for me :( 
As pynput hides the second character after a deadkey from its memory, the trigger is never released.
Does it work for you?

**Comment by logileifs** [comment] 2017-08-19 18:05
well I had not tried it in action yet, only in the interactive interpreter. I just assumed I could catch the deadkeys with something like
```
if key.char == '´' or key.char == '`':
  dead = key.char
# next key release:
combined_char = KeyCode.from_dead('dead').join(KeyCode.from_char(second_key))
```

**Comment by logileifs** [comment] 2017-08-19 18:30
@SpecialCharacter I can confirm that it's working for me with the logic above. It's just some pseudo code with the important bits from my code but if you need further clarification I can post some actual samples from my code, just let me know

**Comment by moses-palmer** [comment] 2017-08-23 19:00
@SpecialCharacter Did the solution provided by @logileifs help you?

**Comment by SpecialCharacter** [comment] 2017-08-23 19:10
Unfortunately no :(
The character I type after the deadkey is not registered in the memory.

Am 23.08.2017 um 21:00 schrieb moses-palmer:
>
> @SpecialCharacter <https://github.com/specialcharacter> Did the 
> solution provided by @logileifs <https://github.com/logileifs> help you?
>
>

**Comment by SpecialCharacter** [comment] 2017-08-23 20:24
Also, now I get a name error:
`m̀ = KeyCode.from_dead(dead).join(KeyCode.from_char('m'))`
`NameError: name 'KeyCode' is not defined`

**Comment by moses-palmer** [comment] 2017-08-24 11:09
You will have to import [`KeyCode`](https://github.com/moses-palmer/pynput/blob/master/lib/pynput/keyboard/_base.py#L37).

**Comment by SpecialCharacter** [comment] 2017-08-24 11:14
Ups… thank you!

**Comment by SpecialCharacter** [comment] 2017-08-24 16:36
Hmm... something is still wrong:
`_base.py", line 49, in __init__`
`'COMBINING ' + unicodedata.name(self.char))`
`TypeError: name() argument 1 must be a unicode character, not str`

**Comment by SpecialCharacter** [comment] 2017-08-24 17:36
Still not working :(
        `if key.char == '`':`
            `dead = key.char`
        `# next key release:`
            `if key == 'm':`
                `m̀ = KeyCode.from_dead(dead).join(KeyCode.from_char('m'))`
                '# dead('`') does not do it either`
                `keyboard.type(m̀.char)`

key ['´'] released
 ´
key Key.shift_r released
key '`' released
 ´`

I type: `m

Why does pynput do the acute when I type the grave?
And the m does not show up?

**Comment by SpecialCharacter** [comment] 2017-08-24 18:22
OK, now the code ALMOST works - if I delete 
`if key == 'm':`
But that means it ALWAYS prints m̀!
How do I get it to respect what character I type after the deadkey?

**Comment by SpecialCharacter** [comment] 2017-08-25 18:54
@logileifs By the way, your m̀ code works!
It just won't let me select the second character… any hint how to do it?

**Comment by SpecialCharacter** [comment] 2017-08-31 07:51
Hi, has somebody come up with a solution how to make the virtual dead key visible to pynput?

**Comment by SpecialCharacter** [comment] 2017-08-31 08:00
Oh, and also Windows splits again ` (grave) into:

    key Key.shift_r released
    key ['´'] released # (acute)

This behaviour is very annoying. Can you think of a way to fix it?

**Comment by SpecialCharacter** [comment] 2017-09-16 22:38
Hi again… so has somebody come up with a solution how to make the _virtual_ dead key (not visible to pynput) into a _real_ dead key? It works in Autohotkey, do why not in Python?

**Comment by moses-palmer** [comment] 2017-09-17 13:51
I have created issue #49 as a container for all *win32 keyboard listener* related issues, as I suspect that the root cause is the same.

I will close this issue. If you think the problem is unrelated to #49, please reopen this issue.

**Closed by moses-palmer** 2017-09-17 13:51 UTC
