### ISSUE TITLE
Mouse position listened is out of screen size

### ISSUE THREAD

**Issue by ODtian** [moses-palmer/pynput#421] opened 2021-11-14 02:45 UTC
**Description**
mouse.Listener on_move event will give a minus coordinate or one bouncing around screen size (not exactly the screen size)
**Platform and pynput version**
Win11 latest

**To Reproduce**
```
def on_move(x, y):
    print(x, y)


listener = mouse.Listener(on_move=on_move)
listener.start()
listener.join()
```

**Comment by moses-palmer** [comment] 2021-11-14 12:12
This is a duplicate of #386.

**Closed by moses-palmer** 2021-11-14 12:12 UTC
